"""三个导出目标。

总原则：**别人的格式一律是导出目标，不是执行路径。** `xirang` 内部只有一条路
走到底，这些只是同一份解析模型的投影。

  core     fusesoc CAPI2。加的段必须是**上游会忽略而不是报错**的，否则
           「产出可被原版 fusesoc 消费」那条铁律就断了
  kconfig  嵌套菜单。装配的每一层都是一个 menu，子包的旋钮自动嵌进去
  tar      零工具依赖的包：生成好的源码 + 一个 Makefile
"""
import io
import pathlib
import tarfile

import yaml

from collections.abc import Iterator

from xirang_core.manifest import GEN_HW
from xirang_core.model import Instance, Resolved

from .doc import to_doc
from .target import Ctx, target


def _sym(*parts) -> str:
    # 档位的取值可能是整数，也可能是 config_pkg::WT 这样的枚举，
    # 符号名一律按字符串拼——收口在这里，调用处不各自 str 一遍
    return "_".join(str(p).upper().replace("-", "_").replace(":", "_")
                    for p in parts if p not in (None, ""))


# ---------------------------------------------------------------- fusesoc

def _describe(res: Resolved, top) -> str:
    s = (top.ip.get("identity") or {}).get("summary", res.top)
    n = sum(1 for _ in res.walk())
    return (f"{s} Generated by xirang from {n} instances; the resolved configuration, "
            f"the address map and the predicted area are in the resolved export.")


def to_core(res: Resolved, pkgs, files: list[str]) -> str:
    top = pkgs[res.top]
    # VLNV 补全：vendor 与 library 都空着的话，两个项目各导一份
    # `::uart:0.1.0` 就在同一个核库里撞名。仍然完全是 CAPI2 的 schema。
    lib = (top.ip.get("identity") or {}).get("category") or "ip"
    d = {
        "name": f"tapeout:{lib}:{res.top}:{top.ip['version']}",
        # 只放 CAPI2 认的键。上游对顶层未知键是**报错**不是忽略
        # （fusesoc 2.4.7 实测：must not contain {'xirang'} properties），
        # 而「别人的格式一律是导出目标」就意味着完全照他们的 schema 来。
        # 我们自己的那份元数据在 resolved 导出里，出处写进 description。
        "description": _describe(res, top),
        "filesets": {
            "rtl": {"files": sorted(files), "file_type": "verilogSource"},
        },
        "targets": {
            "default": {"filesets": ["rtl"]},
        },
    }
    return "CAPI=2:\n" + yaml.safe_dump(d, sort_keys=False, allow_unicode=True)


# ---------------------------------------------------------------- kconfig

def walk(res: Resolved, pkgs) -> "Iterator[tuple[tuple[str, ...], Instance, object, str]]":
    """遍历装配层次，产出 (实例路径, 实例, 它的包, 符号前缀)。

    去程与回程共用这一份：符号名不可逆解（下划线拼接、连字符也变下划线、还全大写），
    所以回来的时候不解析名字，而是把去程再走一遍、边走边查表。
    """
    def rec(insts, path, prefix):
        for i in insts:
            here = (*path, i.name)
            pre = _sym(prefix, i.name)
            yield here, i, pkgs[i.of], pre
            yield from rec(i.children, here, pre)
    yield from rec(res.instances, (), "")


def symtab(res: Resolved, pkgs) -> dict[str, tuple[tuple[str, ...], str, str]]:
    """符号 -> (实例路径, 旋钮名, 取值)。choice 的每个候选各占一个符号，
    最后一项就是它代表的取值；bool 与 int 的最后一项是空串。"""
    out: dict[str, tuple[tuple[str, ...], str, str]] = {}
    for path, inst, pkg, pre in walk(res, pkgs):
        knobs = pkg.knobs()
        for name in inst.values:
            spec = knobs.get(name, {})
            if spec.get("type") == "choice":
                for val in spec["values"]:
                    out[_sym(pre, name, val)] = (path, name, val)
            else:
                out[_sym(pre, name)] = (path, name, "")
    return out


def _cond(prefix: str, when: dict, knobs: dict) -> str:
    """守卫的 when 投影成 Kconfig 的条件表达式。"""
    bits = []
    for k, v in when.items():
        spec = knobs.get(k, {})
        match spec.get("type"):
            case "bool":
                bits.append(f"{'' if v else '!'}{_sym(prefix, k)}")
            case "choice":
                bits.append(_sym(prefix, k, v))
            case _:
                bits.append(f"{_sym(prefix, k)} = {v}")
    return " && ".join(bits) if len(bits) == 1 else "(" + ") && (".join(bits) + ")"


def _condef(prefix: str, spec: dict, knobs: dict) -> list[str]:
    """条件默认值。kconfig 取第一条成立的 default，所以它们排在无条件的前面。"""
    return [f"	default {_kval(spec, c['value'])} if ({_cond(prefix, c['when'], knobs)})"
            for c in spec.get("when_default") or []]


def _kval(spec: dict, v):
    return ("y" if v else "n") if isinstance(v, bool) else v


def _gates(pkg, prefix: str, name: str, knobs: dict) -> tuple[list[str], list[str]]:
    """这个旋钮被哪些守卫收窄。返回 (条目内的行, choice 里逐档的 depends)。

    Kconfig 原本就有这套语义，我们不另造：条件成立时符号**不可选**
    （`depends on !(条件)`），同时 `default … if 条件` 把它钉在允许的那个值上——
    kconfig 里看不见的符号照样取默认值，于是「不可选」与「只能是这个」是一件事。
    """
    lines: list[str] = []
    per_val: list[str] = []
    spec = knobs.get(name, {})
    for g in pkg.guards():
        keep = g["narrow"].get(name)
        if keep is None:
            continue
        c = _cond(prefix, g["when"], knobs)
        match spec.get("type"):
            case "choice":
                per_val += [f"{v}		depends on !({c})"
                            for v in spec.get("values", []) if v not in keep]
            case "bool":
                lines.append(f"	depends on !({c})")
                lines.append(f"	default {'y' if keep[0] else 'n'} if ({c})")
            case _:
                lines.append(f"	range {min(keep)} {max(keep)} if ({c})"
                             if len(keep) > 1 else f"	depends on !({c})")
                if len(keep) == 1:
                    lines.append(f"	default {keep[0]} if ({c})")
        lines.append(f"	comment \"{g['why']}\"" if False else "")
        lines.pop()
    return lines, per_val


def _knob_entries(inst: Instance, pkg, prefix: str,
                  chipsym: dict | None = None) -> list[str]:
    L = []
    knobs = pkg.knobs()
    chipsym = chipsym or {}
    up = pkg.inherits()
    for name, v in inst.values.items():
        spec = knobs.get(name, {})
        sym = _sym(prefix, name)
        desc = spec.get("desc") or name
        if spec.get("type") == "bool":
            L += [f'config {sym}'] + (
                ["	bool"] if up.get(name, {}).get("lock")
                else [f'	bool "{desc}"'])
            if (c := chipsym.get(name)) and name in up:
                L.append(f"	default {c}")
            L += _condef(prefix, spec, knobs)
            L.append(f'	default {"y" if v.value else "n"}')
            for dep in spec.get("depends", []) or []:
                L.append(f"	depends on {_sym(prefix, dep)}")
            L += _gates(pkg, prefix, name, knobs)[0]
            if v.area_um2:
                # 一行一条，别在 f-string 里塞换行
                L.append("	help")
                L.append(f"	  Costs about {v.area_um2:.0f} um2 at this setting.")
        elif spec.get("type") == "choice":
            # default 不能省：省了当前选的是哪一档就没导出去，往返一圈值必丢
            L += ['choice', f'	prompt "{desc}"']
            # 档位型的芯片级旋钮逐档跟随：kconfig 取第一条成立的 default
            if name in up and name in chipsym:
                L += [f'	default {_sym(prefix, name, val)} '
                      f'if {_sym("CHIP", name, val)}'
                      for val in spec["values"]]
            L.append(f'	default {_sym(prefix, name, v.value)}')
            per = dict(x.split("	", 1) for x in _gates(pkg, prefix, name, knobs)[1])
            for val in spec["values"]:
                L.append(f'	config {_sym(prefix, name, val)}')
                L.append(f'		bool "{val}"')
                if val in per:
                    L.append("	" + per[val])
            L.append("endchoice")
        else:
            L += [f'config {sym}'] + (
                ["	int"] if up.get(name, {}).get("lock")
                else [f'	int "{desc}"'])
            if (c := chipsym.get(name)) and name in up:
                L.append(f"	default {c}")
            L += _condef(prefix, spec, knobs)
            L.append(f'	default {v.value}')
            # 条件区间要排在无条件区间前面：kconfig 取第一条成立的
            L += _gates(pkg, prefix, name, knobs)[0]
            r = spec.get("range")
            if r:
                L.append(f"	range {r[0]} {r[1]}")
        L.append("")
    return L


def _chip(res: Resolved, pkgs) -> tuple[list[str], dict[str, str]]:
    """芯片级的旋钮在顶上各占一个符号，后代 `default` 到它身上。"""
    seen: dict[str, dict] = {}
    for _, _, pkg, _ in walk(res, pkgs):
        for k, spec in pkg.inherits().items():
            seen.setdefault(k, spec)
    # 顶层 chip: 定过的，菜单里的默认就该是它——否则菜单说的与解出来的不是一件事
    top = pkgs.get(res.top)
    fixed = top.chip() if top is not None and hasattr(top, "chip") else {}
    for k, v in fixed.items():
        if k in seen:
            seen[k] = {**seen[k], "default": v}
    if not seen:
        return [], {}
    L = ['menu "芯片级 —— 一颗芯片只有一个说法"']
    sym = {}
    for k, spec in sorted(seen.items()):
        sy = _sym("CHIP", k)
        sym[k] = sy
        desc = spec.get("desc") or k
        if spec.get("type") == "choice":
            L += ["choice", f'	prompt "{desc}"',
                  f'	default {_sym("CHIP", k, spec["default"])}']
            for v in spec["values"]:
                L += [f'	config {_sym("CHIP", k, v)}', f'		bool "{v}"']
            L.append("endchoice")
        elif spec.get("type") == "bool" or isinstance(spec.get("default"), bool):
            L += [f"config {sy}", f'	bool "{desc}"',
                  f'	default {"y" if spec.get("default") else "n"}']
        else:
            L += [f"config {sy}", f'	int "{desc}"',
                  f'	default {spec.get("default", 0)}']
        L.append("")
    L += ["endmenu", ""]
    return L, sym


def to_kconfig(res: Resolved, pkgs) -> str:
    """装配的每一层是一个 menu，子包的旋钮自动嵌进去，深度不限。"""
    L = ["# 由 xirang 生成。菜单层次与装配层次一一对应。",
         f'mainmenu "{res.top}"', ""]
    chip, CHIPSYM = _chip(res, pkgs)
    L += chip

    def rec(insts, depth, prefix):
        for i in insts:
            p = pkgs[i.of]
            title = (p.ip.get("identity") or {}).get("display_name", i.of)
            addr = f"  @ {i.addr:#010x}" if i.addr is not None else ""
            L.append(f'menu "{i.name} — {title}{addr}"')
            L.extend(_knob_entries(i, p, _sym(prefix, i.name),
                                   CHIPSYM))
            if i.children:
                rec(i.children, depth + 1, _sym(prefix, i.name))
            L.append("endmenu")
            L.append("")

    rec(res.instances, 0, "")
    return "\n".join(L)


# ---------------------------------------------------------------- tar

MAKEFILE = """# 由 xirang 生成。这个包不依赖 xirang，只要 bsc 就能重跑。
TOP  ?= {top}
BSC  ?= bsc
VDIR ?= rtl

all: $(VDIR)/$(TOP).v

$(VDIR)/$(TOP).v: $(wildcard hwsrc/*.bsv)
\tmkdir -p $(VDIR) build
\t$(BSC) -verilog -u -vdir $(VDIR) -bdir build -info-dir build -p hwsrc:+ -g $(TOP) hwsrc/{topsrc}

clean:
\trm -rf $(VDIR) build

.PHONY: all clean
"""


def to_tar(res: Resolved, pkgs, build_dir: pathlib.Path, out: pathlib.Path,
           top_module: str) -> int:
    """零工具依赖的包。判据是：解开之后只要 bsc 就能重跑，不需要 xirang。"""
    n = 0
    with tarfile.open(out, "w:gz") as tf:
        for f in sorted((build_dir / GEN_HW).glob("*.bsv")):
            tf.add(f, arcname=f"{res.top}/{GEN_HW}/{f.name}")
            n += 1
        for name in sorted({i.of for _, i in res.walk()}) + [res.top]:
            p = pkgs.get(name)
            if not p:
                continue
            src = next(iter(p.dirs("hwsrc")), p.root / GEN_HW)
            if src.is_dir():
                for f in sorted(list(src.glob("*.bsv"))
                                + list(src.glob("*.bs"))):
                    tf.add(f, arcname=f"{res.top}/{GEN_HW}/{f.name}")
                    n += 1
            for m in ("ip.yaml", "regmap.yaml"):
                q = p.root / m
                if q.exists():
                    tf.add(q, arcname=f"{res.top}/manifests/{name}-{m}")
        for extra in ("regmap.json", "addr_map.md"):
            q = build_dir / extra
            if q.exists():
                tf.add(q, arcname=f"{res.top}/{extra}")
        mk = MAKEFILE.format(top=top_module, topsrc=f"{top_module[2:]}Pkg.bsv")
        info = tarfile.TarInfo(f"{res.top}/Makefile")
        data = mk.encode()
        info.size = len(data)
        tf.addfile(info, io.BytesIO(data))
    return n


# ---------------------------------------------------------------- 注册

# 三个老导出器的形状各不相同，这里各套一层薄壳收进同一张表。
# 加第四、第五种格式只往表里加一行，`cmd_export` 一个字不用动。

@target(name="resolved", ext=".yaml", desc="解出来的配置：每个旋钮的最终值与来历")
def _resolved(ctx: Ctx) -> str:
    return yaml.safe_dump(to_doc(ctx.res), sort_keys=False, allow_unicode=True)


@target(name="core", ext=".core", desc="FuseSoC CAPI2，上游 fusesoc 直接吃",
        needs=("rtl",))
def _core(ctx: Ctx) -> str:
    files = sorted(f.name for f in (ctx.build / "rtl").glob("*.v"))
    return to_core(ctx.res, ctx.pkgs, files)


@target(name="kconfig", ext=".kconfig", desc="嵌套菜单，喂 menuconfig；有回程")
def _kconfig(ctx: Ctx) -> str:
    return to_kconfig(ctx.res, ctx.pkgs)


@target(name="tar", ext=".tar.gz", desc="零工具依赖的源码包，解开只要 bsc",
        needs=("build",))
def _tar(ctx: Ctx) -> bytes:
    import tempfile
    top = "mk" + "".join(w.capitalize()
                         for w in ctx.res.top.replace("-", "_").split("_"))
    with tempfile.TemporaryDirectory() as d:
        f = pathlib.Path(d) / "x.tar.gz"
        to_tar(ctx.res, ctx.pkgs, ctx.build, f, top)
        return f.read_bytes()


from . import ipxact as _ipxact   # noqa: E402,F401  注册用
from . import rdl as _rdl         # noqa: E402,F401
