//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Tue Sep 22 00:42:12 JST 2026
//
//
// Ports:
// Name                         I/O  size props
// regs_access                    O    33
// RDY_regs_access                O     1 const
// pins_sck                       O     1
// pins_cs_n                      O     1
// pins_io_o                      O     4
// pins_io_oe                     O     4
// irq                            O     1
// clk                            I     1 clock
// rst_n                          I     1 reset
// regs_access_r                  I    45
// pins_io_i                      I     4
// EN_regs_access                 I     1
//
// Combinational paths from inputs to outputs:
//   regs_access_r -> regs_access
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkSpiBareLines4_8_1_4(clk,
			     rst_n,

			     regs_access_r,
			     EN_regs_access,
			     regs_access,
			     RDY_regs_access,

			     pins_sck,

			     pins_cs_n,

			     pins_io_o,

			     pins_io_oe,

			     pins_io_i,

			     irq);
  input  clk;
  input  rst_n;

  // actionvalue method regs_access
  input  [44 : 0] regs_access_r;
  input  EN_regs_access;
  output [32 : 0] regs_access;
  output RDY_regs_access;

  // value method pins_sck
  output pins_sck;

  // value method pins_cs_n
  output pins_cs_n;

  // value method pins_io_o
  output [3 : 0] pins_io_o;

  // value method pins_io_oe
  output [3 : 0] pins_io_oe;

  // action method pins_io_i
  input  [3 : 0] pins_io_i;

  // value method irq
  output irq;

  // signals for module outputs
  wire [32 : 0] regs_access;
  wire [3 : 0] pins_io_o, pins_io_oe;
  wire RDY_regs_access, irq, pins_cs_n, pins_sck;

  // inlined wires
  wire m_csDrop$EN_port0__write,
       m_csDrop$port1__read,
       m_csDrop$port2__read,
       m_r_rxdata_data_acc$whas,
       m_r_txdata_data_mod$whas;

  // register m_bitn
  reg [3 : 0] m_bitn;
  wire [3 : 0] m_bitn$D_IN;
  wire m_bitn$EN;

  // register m_csAct
  reg m_csAct;
  wire m_csAct$D_IN, m_csAct$EN;

  // register m_csDrop
  reg m_csDrop;
  wire m_csDrop$D_IN, m_csDrop$EN;

  // register m_csOn
  reg m_csOn;
  wire m_csOn$D_IN, m_csOn$EN;

  // register m_defWas
  reg m_defWas;
  wire m_defWas$D_IN, m_defWas$EN;

  // register m_div
  reg [11 : 0] m_div;
  wire [11 : 0] m_div$D_IN;
  wire m_div$EN;

  // register m_dly
  reg [7 : 0] m_dly;
  reg [7 : 0] m_dly$D_IN;
  wire m_dly$EN;

  // register m_half
  reg m_half;
  wire m_half$D_IN, m_half$EN;

  // register m_idWas
  reg m_idWas;
  wire m_idWas$D_IN, m_idWas$EN;

  // register m_modeWas
  reg [1 : 0] m_modeWas;
  wire [1 : 0] m_modeWas$D_IN;
  wire m_modeWas$EN;

  // register m_r_csdef_r
  reg m_r_csdef_r;
  wire m_r_csdef_r$D_IN, m_r_csdef_r$EN;

  // register m_r_csid_r
  reg m_r_csid_r;
  wire m_r_csid_r$D_IN, m_r_csid_r$EN;

  // register m_r_csmode_r
  reg [1 : 0] m_r_csmode_r;
  wire [1 : 0] m_r_csmode_r$D_IN;
  wire m_r_csmode_r$EN;

  // register m_r_delay0_cssck_r
  reg [7 : 0] m_r_delay0_cssck_r;
  wire [7 : 0] m_r_delay0_cssck_r$D_IN;
  wire m_r_delay0_cssck_r$EN;

  // register m_r_delay0_sckcs_r
  reg [7 : 0] m_r_delay0_sckcs_r;
  wire [7 : 0] m_r_delay0_sckcs_r$D_IN;
  wire m_r_delay0_sckcs_r$EN;

  // register m_r_delay1_intercs_r
  reg [7 : 0] m_r_delay1_intercs_r;
  wire [7 : 0] m_r_delay1_intercs_r$D_IN;
  wire m_r_delay1_intercs_r$EN;

  // register m_r_delay1_interxfr_r
  reg [7 : 0] m_r_delay1_interxfr_r;
  wire [7 : 0] m_r_delay1_interxfr_r$D_IN;
  wire m_r_delay1_interxfr_r$EN;

  // register m_r_fmt_dir_r
  reg m_r_fmt_dir_r;
  wire m_r_fmt_dir_r$D_IN, m_r_fmt_dir_r$EN;

  // register m_r_fmt_endian_r
  reg m_r_fmt_endian_r;
  wire m_r_fmt_endian_r$D_IN, m_r_fmt_endian_r$EN;

  // register m_r_fmt_len_r
  reg [3 : 0] m_r_fmt_len_r;
  wire [3 : 0] m_r_fmt_len_r$D_IN;
  wire m_r_fmt_len_r$EN;

  // register m_r_fmt_proto_r
  reg [1 : 0] m_r_fmt_proto_r;
  wire [1 : 0] m_r_fmt_proto_r$D_IN;
  wire m_r_fmt_proto_r$EN;

  // register m_r_ie_rxwm_r
  reg m_r_ie_rxwm_r;
  wire m_r_ie_rxwm_r$D_IN, m_r_ie_rxwm_r$EN;

  // register m_r_ie_txwm_r
  reg m_r_ie_txwm_r;
  wire m_r_ie_txwm_r$D_IN, m_r_ie_txwm_r$EN;

  // register m_r_rxmark_r
  reg [2 : 0] m_r_rxmark_r;
  wire [2 : 0] m_r_rxmark_r$D_IN;
  wire m_r_rxmark_r$EN;

  // register m_r_sckdiv_r
  reg [11 : 0] m_r_sckdiv_r;
  wire [11 : 0] m_r_sckdiv_r$D_IN;
  wire m_r_sckdiv_r$EN;

  // register m_r_sckmode_pha_r
  reg m_r_sckmode_pha_r;
  wire m_r_sckmode_pha_r$D_IN, m_r_sckmode_pha_r$EN;

  // register m_r_sckmode_pol_r
  reg m_r_sckmode_pol_r;
  wire m_r_sckmode_pol_r$D_IN, m_r_sckmode_pol_r$EN;

  // register m_r_txdata_data_r
  reg [7 : 0] m_r_txdata_data_r;
  wire [7 : 0] m_r_txdata_data_r$D_IN;
  wire m_r_txdata_data_r$EN;

  // register m_r_txmark_r
  reg [2 : 0] m_r_txmark_r;
  wire [2 : 0] m_r_txmark_r$D_IN;
  wire m_r_txmark_r$EN;

  // register m_rxIn
  reg [7 : 0] m_rxIn;
  wire [7 : 0] m_rxIn$D_IN;
  wire m_rxIn$EN;

  // register m_rxOut
  reg [7 : 0] m_rxOut;
  wire [7 : 0] m_rxOut$D_IN;
  wire m_rxOut$EN;

  // register m_shRx
  reg [7 : 0] m_shRx;
  wire [7 : 0] m_shRx$D_IN;
  wire m_shRx$EN;

  // register m_shTx
  reg [7 : 0] m_shTx;
  wire [7 : 0] m_shTx$D_IN;
  wire m_shTx$EN;

  // register m_st
  reg [2 : 0] m_st;
  reg [2 : 0] m_st$D_IN;
  wire m_st$EN;

  // register m_txIn
  reg [7 : 0] m_txIn;
  wire [7 : 0] m_txIn$D_IN;
  wire m_txIn$EN;

  // register m_txOut
  reg [7 : 0] m_txOut;
  wire [7 : 0] m_txOut$D_IN;
  wire m_txOut$EN;

  // register m_txPend
  reg m_txPend;
  wire m_txPend$D_IN, m_txPend$EN;

  // ports of submodule m_rxq
  wire [7 : 0] m_rxq$D_IN, m_rxq$D_OUT;
  wire m_rxq$CLR, m_rxq$DEQ, m_rxq$EMPTY_N, m_rxq$ENQ, m_rxq$FULL_N;

  // ports of submodule m_txq
  wire [7 : 0] m_txq$D_IN, m_txq$D_OUT;
  wire m_txq$CLR, m_txq$DEQ, m_txq$EMPTY_N, m_txq$ENQ, m_txq$FULL_N;

  // rule scheduling signals
  wire WILL_FIRE_RL_m_load, WILL_FIRE_RL_m_tick, WILL_FIRE_RL_m_waited;

  // inputs to muxes for submodule ports
  reg [7 : 0] MUX_m_dly$write_1__VAL_4;
  reg [2 : 0] MUX_m_st$write_1__VAL_2, MUX_m_st$write_1__VAL_3;
  wire [11 : 0] MUX_m_div$write_1__VAL_4;
  wire [7 : 0] MUX_m_dly$write_1__VAL_2,
	       MUX_m_dly$write_1__VAL_3,
	       MUX_m_shTx$write_1__VAL_1;
  wire [2 : 0] MUX_m_st$write_1__VAL_1;
  wire MUX_m_bitn$write_1__SEL_1,
       MUX_m_csOn$write_1__SEL_1,
       MUX_m_csOn$write_1__SEL_2,
       MUX_m_div$write_1__SEL_2,
       MUX_m_dly$write_1__SEL_3,
       MUX_m_dly$write_1__SEL_4,
       MUX_m_half$write_1__PSEL_2,
       MUX_m_half$write_1__SEL_2,
       MUX_m_st$write_1__SEL_1;

  // remaining internal signals
  reg [31 : 0] y_avValue_rdata__h17448;
  wire [31 : 0] _theResult___snd__h17453,
		cur__h10560,
		cur__h11702,
		cur__h12996,
		cur__h16250,
		cur__h17451,
		cur__h5189,
		cur__h9423,
		rd__h14201,
		rd__h15234,
		rd__h4165,
		rd__h6341,
		rd__h7374,
		rd__h8403,
		v__h14115,
		y_avValue_snd__h10558,
		y_avValue_snd__h11691,
		y_avValue_snd__h12994,
		y_avValue_snd__h14096,
		y_avValue_snd__h14186,
		y_avValue_snd__h15219,
		y_avValue_snd__h16248,
		y_avValue_snd__h17383,
		y_avValue_snd__h5187,
		y_avValue_snd__h6326,
		y_avValue_snd__h7359,
		y_avValue_snd__h8388,
		y_avValue_snd__h9421;
  wire [11 : 0] x__h3408;
  wire [7 : 0] IF_m_r_fmt_endian_r_THEN_m_shTx_ELSE_0_CONCAT__ETC__q1,
	       IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d157,
	       IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d190,
	       IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d219,
	       IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q2,
	       IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q3,
	       IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q4,
	       IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q6,
	       IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q8,
	       IF_regs_access_r_BIT_1_THEN_regs_access_r_BITS_ETC__q7,
	       IF_regs_access_r_BIT_2_THEN_regs_access_r_BITS_ETC__q5,
	       rxLevel__h2182,
	       txLevel__h2181,
	       y__h17614,
	       y__h17630;
  wire [4 : 0] nxt__h3484;
  wire [3 : 0] flen__h2185;
  wire NOT_m_r_csid_r_EQ_m_idWas_1_2_3_OR_NOT_m_r_csm_ETC___d22,
       _0_CONCAT_m_bitn_8_9_PLUS_4_0_ULT_0_CONCAT_IF_m_ETC___d85,
       m_csOn_read__3_AND_m_csDrop_port1__read__7_OR__ETC___d36,
       m_csOn_read__3_AND_m_csDrop_port1__read__7_OR__ETC___d43,
       m_half_9_AND_NOT_0_CONCAT_m_bitn_8_9_PLUS_4_0__ETC___d102,
       v__h3824,
       v__h3850,
       x__h17539,
       x__h2403,
       x_wget__h1064,
       x_wget__h644,
       x_wget__h786,
       x_wget__h993,
       y__h2693;

  // actionvalue method regs_access
  assign regs_access =
	     { y_avValue_rdata__h17448,
	       regs_access_r[44:37] != 8'h0 &&
	       regs_access_r[44:37] != 8'h04 &&
	       regs_access_r[44:37] != 8'h10 &&
	       regs_access_r[44:37] != 8'h14 &&
	       regs_access_r[44:37] != 8'h18 &&
	       regs_access_r[44:37] != 8'h28 &&
	       regs_access_r[44:37] != 8'h2C &&
	       regs_access_r[44:37] != 8'h40 &&
	       regs_access_r[44:37] != 8'h48 &&
	       regs_access_r[44:37] != 8'h4C &&
	       regs_access_r[44:37] != 8'h50 &&
	       regs_access_r[44:37] != 8'h54 &&
	       regs_access_r[44:37] != 8'h70 &&
	       regs_access_r[44:37] != 8'h74 } ;
  assign RDY_regs_access = 1'd1 ;

  // value method pins_sck
  assign pins_sck = (m_st == 3'd3) ? x__h17539 ^ m_half : m_r_sckmode_pol_r ;

  // value method pins_cs_n
  assign pins_cs_n =
	     (m_csOn && m_r_csmode_r != 2'd3) ? m_csAct : m_r_csdef_r ;

  // value method pins_io_o
  assign pins_io_o =
	     IF_m_r_fmt_endian_r_THEN_m_shTx_ELSE_0_CONCAT__ETC__q1[3:0] ;

  // value method pins_io_oe
  assign pins_io_oe = m_r_fmt_dir_r ? 4'd15 : 4'd0 ;

  // value method irq
  assign irq = m_r_ie_txwm_r && v__h3824 || m_r_ie_rxwm_r && v__h3850 ;

  // submodule m_rxq
  SizedFIFO #(.p1width(32'd8),
	      .p2depth(32'd8),
	      .p3cntr_width(32'd3),
	      .guarded(1'd1)) m_rxq(.RST(rst_n),
				    .CLK(clk),
				    .D_IN(m_rxq$D_IN),
				    .ENQ(m_rxq$ENQ),
				    .DEQ(m_rxq$DEQ),
				    .CLR(m_rxq$CLR),
				    .D_OUT(m_rxq$D_OUT),
				    .FULL_N(m_rxq$FULL_N),
				    .EMPTY_N(m_rxq$EMPTY_N));

  // submodule m_txq
  SizedFIFO #(.p1width(32'd8),
	      .p2depth(32'd8),
	      .p3cntr_width(32'd3),
	      .guarded(1'd1)) m_txq(.RST(rst_n),
				    .CLK(clk),
				    .D_IN(m_txq$D_IN),
				    .ENQ(m_txq$ENQ),
				    .DEQ(m_txq$DEQ),
				    .CLR(m_txq$CLR),
				    .D_OUT(m_txq$D_OUT),
				    .FULL_N(m_txq$FULL_N),
				    .EMPTY_N(m_txq$EMPTY_N));

  // rule RL_m_tick
  assign WILL_FIRE_RL_m_tick =
	     (m_st == 3'd1 || m_st == 3'd4 || m_st == 3'd5 || m_st == 3'd6) &&
	     m_dly != 8'd0 ;

  // rule RL_m_waited
  assign WILL_FIRE_RL_m_waited =
	     (m_st == 3'd1 || m_st == 3'd4 || m_st == 3'd5 || m_st == 3'd6) &&
	     m_dly == 8'd0 ;

  // rule RL_m_load
  assign WILL_FIRE_RL_m_load = m_txq$EMPTY_N && m_st == 3'd2 ;

  // inputs to muxes for submodule ports
  assign MUX_m_bitn$write_1__SEL_1 =
	     m_st == 3'd3 && m_div == 12'd0 && m_half &&
	     _0_CONCAT_m_bitn_8_9_PLUS_4_0_ULT_0_CONCAT_IF_m_ETC___d85 ;
  assign MUX_m_csOn$write_1__SEL_1 =
	     m_st == 3'd0 && m_txq$EMPTY_N && !m_csOn &&
	     m_r_csmode_r != 2'd3 ;
  assign MUX_m_csOn$write_1__SEL_2 = WILL_FIRE_RL_m_waited && m_st == 3'd4 ;
  assign MUX_m_div$write_1__SEL_2 =
	     m_st == 3'd0 &&
	     m_csOn_read__3_AND_m_csDrop_port1__read__7_OR__ETC___d43 ;
  assign MUX_m_dly$write_1__SEL_3 =
	     WILL_FIRE_RL_m_tick && m_div == 12'd0 && m_half ;
  assign MUX_m_dly$write_1__SEL_4 =
	     m_st == 3'd3 && m_div == 12'd0 && m_half &&
	     !_0_CONCAT_m_bitn_8_9_PLUS_4_0_ULT_0_CONCAT_IF_m_ETC___d85 ;
  assign MUX_m_half$write_1__PSEL_2 = m_st == 3'd3 || WILL_FIRE_RL_m_tick ;
  assign MUX_m_half$write_1__SEL_2 =
	     MUX_m_half$write_1__PSEL_2 && m_div == 12'd0 ;
  assign MUX_m_st$write_1__SEL_1 =
	     m_st == 3'd0 &&
	     m_csOn_read__3_AND_m_csDrop_port1__read__7_OR__ETC___d36 ;
  assign MUX_m_div$write_1__VAL_4 =
	     (m_div == 12'd0) ? m_r_sckdiv_r : x__h3408 ;
  assign MUX_m_dly$write_1__VAL_2 =
	     (m_csOn &&
	      (m_csDrop$port1__read ||
	       m_r_csmode_r != 2'd2 && m_r_csmode_r != 2'd3)) ?
	       m_r_delay0_sckcs_r :
	       m_r_delay0_cssck_r ;
  assign MUX_m_dly$write_1__VAL_3 = m_dly - 8'd1 ;
  always@(m_r_csmode_r or m_r_delay0_sckcs_r or m_r_delay1_interxfr_r)
  begin
    case (m_r_csmode_r)
      2'd2, 2'd3: MUX_m_dly$write_1__VAL_4 = m_r_delay1_interxfr_r;
      default: MUX_m_dly$write_1__VAL_4 = m_r_delay0_sckcs_r;
    endcase
  end
  assign MUX_m_shTx$write_1__VAL_1 =
	     m_r_fmt_endian_r ?
	       { 4'd0, m_shTx[7:4] } :
	       { m_shTx[3:0], 4'd0 } ;
  assign MUX_m_st$write_1__VAL_1 =
	     (m_csOn &&
	      (m_csDrop$port1__read ||
	       m_r_csmode_r != 2'd2 && m_r_csmode_r != 2'd3)) ?
	       3'd4 :
	       ((m_csOn || m_r_csmode_r == 2'd3) ? 3'd2 : 3'd1) ;
  always@(m_r_csmode_r)
  begin
    case (m_r_csmode_r)
      2'd2, 2'd3: MUX_m_st$write_1__VAL_2 = 3'd6;
      default: MUX_m_st$write_1__VAL_2 = 3'd4;
    endcase
  end
  always@(m_st)
  begin
    case (m_st)
      3'd1: MUX_m_st$write_1__VAL_3 = 3'd2;
      3'd4: MUX_m_st$write_1__VAL_3 = 3'd5;
      default: MUX_m_st$write_1__VAL_3 = 3'd0;
    endcase
  end

  // inlined wires
  assign m_r_txdata_data_mod$whas =
	     EN_regs_access && regs_access_r[44:37] == 8'h48 &&
	     regs_access_r[36] ;
  assign m_r_rxdata_data_acc$whas =
	     EN_regs_access && regs_access_r[44:37] == 8'h4C &&
	     !regs_access_r[36] ;
  assign m_csDrop$EN_port0__write =
	     NOT_m_r_csid_r_EQ_m_idWas_1_2_3_OR_NOT_m_r_csm_ETC___d22 &&
	     m_csOn ;
  assign m_csDrop$port1__read = m_csDrop$EN_port0__write || m_csDrop ;
  assign m_csDrop$port2__read =
	     !MUX_m_csOn$write_1__SEL_2 && m_csDrop$port1__read ;

  // register m_bitn
  assign m_bitn$D_IN = MUX_m_bitn$write_1__SEL_1 ? nxt__h3484[3:0] : 4'd0 ;
  assign m_bitn$EN =
	     m_st == 3'd3 && m_div == 12'd0 && m_half &&
	     _0_CONCAT_m_bitn_8_9_PLUS_4_0_ULT_0_CONCAT_IF_m_ETC___d85 ||
	     WILL_FIRE_RL_m_load ;

  // register m_csAct
  assign m_csAct$D_IN = m_r_csdef_r ^ y__h2693 ;
  assign m_csAct$EN = MUX_m_csOn$write_1__SEL_1 ;

  // register m_csDrop
  assign m_csDrop$D_IN = m_csDrop$port2__read ;
  assign m_csDrop$EN = 1'b1 ;

  // register m_csOn
  assign m_csOn$D_IN = MUX_m_csOn$write_1__SEL_1 ;
  assign m_csOn$EN =
	     m_st == 3'd0 && m_txq$EMPTY_N && !m_csOn &&
	     m_r_csmode_r != 2'd3 ||
	     WILL_FIRE_RL_m_waited && m_st == 3'd4 ;

  // register m_defWas
  assign m_defWas$D_IN = m_r_csdef_r ;
  assign m_defWas$EN = 1'd1 ;

  // register m_div
  assign m_div$D_IN =
	     (MUX_m_csOn$write_1__SEL_2 || MUX_m_div$write_1__SEL_2 ||
	      WILL_FIRE_RL_m_load) ?
	       m_r_sckdiv_r :
	       MUX_m_div$write_1__VAL_4 ;
  assign m_div$EN =
	     WILL_FIRE_RL_m_waited && m_st == 3'd4 ||
	     m_st == 3'd0 &&
	     m_csOn_read__3_AND_m_csDrop_port1__read__7_OR__ETC___d43 ||
	     WILL_FIRE_RL_m_load ||
	     m_st == 3'd3 ||
	     WILL_FIRE_RL_m_tick ;

  // register m_dly
  always@(MUX_m_csOn$write_1__SEL_2 or
	  m_r_delay1_intercs_r or
	  MUX_m_div$write_1__SEL_2 or
	  MUX_m_dly$write_1__VAL_2 or
	  MUX_m_dly$write_1__SEL_3 or
	  MUX_m_dly$write_1__VAL_3 or
	  MUX_m_dly$write_1__SEL_4 or MUX_m_dly$write_1__VAL_4)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_m_csOn$write_1__SEL_2: m_dly$D_IN = m_r_delay1_intercs_r;
      MUX_m_div$write_1__SEL_2: m_dly$D_IN = MUX_m_dly$write_1__VAL_2;
      MUX_m_dly$write_1__SEL_3: m_dly$D_IN = MUX_m_dly$write_1__VAL_3;
      MUX_m_dly$write_1__SEL_4: m_dly$D_IN = MUX_m_dly$write_1__VAL_4;
      default: m_dly$D_IN = 8'b10101010 /* unspecified value */ ;
    endcase
  end
  assign m_dly$EN =
	     WILL_FIRE_RL_m_waited && m_st == 3'd4 ||
	     m_st == 3'd0 &&
	     m_csOn_read__3_AND_m_csDrop_port1__read__7_OR__ETC___d43 ||
	     WILL_FIRE_RL_m_tick && m_div == 12'd0 && m_half ||
	     m_st == 3'd3 && m_div == 12'd0 && m_half &&
	     !_0_CONCAT_m_bitn_8_9_PLUS_4_0_ULT_0_CONCAT_IF_m_ETC___d85 ;

  // register m_half
  assign m_half$D_IN = MUX_m_half$write_1__SEL_2 && !m_half ;
  assign m_half$EN =
	     WILL_FIRE_RL_m_waited && m_st == 3'd4 ||
	     (m_st == 3'd3 || WILL_FIRE_RL_m_tick) && m_div == 12'd0 ||
	     m_st == 3'd0 &&
	     m_csOn_read__3_AND_m_csDrop_port1__read__7_OR__ETC___d43 ||
	     WILL_FIRE_RL_m_load ;

  // register m_idWas
  assign m_idWas$D_IN = m_r_csid_r ;
  assign m_idWas$EN = 1'd1 ;

  // register m_modeWas
  assign m_modeWas$D_IN = m_r_csmode_r ;
  assign m_modeWas$EN = 1'd1 ;

  // register m_r_csdef_r
  assign m_r_csdef_r$D_IN =
	     IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q2[0] ;
  assign m_r_csdef_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h14 &&
	     regs_access_r[36] ;

  // register m_r_csid_r
  assign m_r_csid_r$D_IN =
	     IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q3[0] ;
  assign m_r_csid_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h10 &&
	     regs_access_r[36] ;

  // register m_r_csmode_r
  assign m_r_csmode_r$D_IN =
	     IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q4[1:0] ;
  assign m_r_csmode_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h18 &&
	     regs_access_r[36] ;

  // register m_r_delay0_cssck_r
  assign m_r_delay0_cssck_r$D_IN =
	     regs_access_r[0] ? regs_access_r[11:4] : m_r_delay0_cssck_r ;
  assign m_r_delay0_cssck_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h28 &&
	     regs_access_r[36] ;

  // register m_r_delay0_sckcs_r
  assign m_r_delay0_sckcs_r$D_IN =
	     regs_access_r[2] ? regs_access_r[27:20] : m_r_delay0_sckcs_r ;
  assign m_r_delay0_sckcs_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h28 &&
	     regs_access_r[36] ;

  // register m_r_delay1_intercs_r
  assign m_r_delay1_intercs_r$D_IN =
	     regs_access_r[0] ? regs_access_r[11:4] : m_r_delay1_intercs_r ;
  assign m_r_delay1_intercs_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h2C &&
	     regs_access_r[36] ;

  // register m_r_delay1_interxfr_r
  assign m_r_delay1_interxfr_r$D_IN =
	     regs_access_r[2] ? regs_access_r[27:20] : m_r_delay1_interxfr_r ;
  assign m_r_delay1_interxfr_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h2C &&
	     regs_access_r[36] ;

  // register m_r_fmt_dir_r
  assign m_r_fmt_dir_r$D_IN =
	     IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d190[3] ;
  assign m_r_fmt_dir_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h40 &&
	     regs_access_r[36] ;

  // register m_r_fmt_endian_r
  assign m_r_fmt_endian_r$D_IN =
	     IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d190[2] ;
  assign m_r_fmt_endian_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h40 &&
	     regs_access_r[36] ;

  // register m_r_fmt_len_r
  assign m_r_fmt_len_r$D_IN =
	     IF_regs_access_r_BIT_2_THEN_regs_access_r_BITS_ETC__q5[3:0] ;
  assign m_r_fmt_len_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h40 &&
	     regs_access_r[36] &&
	     IF_regs_access_r_BIT_2_THEN_regs_access_r_BITS_ETC__q5[3:0] <=
	     4'd8 ;

  // register m_r_fmt_proto_r
  assign m_r_fmt_proto_r$D_IN =
	     IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d190[1:0] ;
  assign m_r_fmt_proto_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h40 &&
	     regs_access_r[36] ;

  // register m_r_ie_rxwm_r
  assign m_r_ie_rxwm_r$D_IN =
	     IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d219[1] ;
  assign m_r_ie_rxwm_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h70 &&
	     regs_access_r[36] ;

  // register m_r_ie_txwm_r
  assign m_r_ie_txwm_r$D_IN =
	     IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d219[0] ;
  assign m_r_ie_txwm_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h70 &&
	     regs_access_r[36] ;

  // register m_r_rxmark_r
  assign m_r_rxmark_r$D_IN =
	     IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q6[2:0] ;
  assign m_r_rxmark_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h54 &&
	     regs_access_r[36] ;

  // register m_r_sckdiv_r
  assign m_r_sckdiv_r$D_IN =
	     { IF_regs_access_r_BIT_1_THEN_regs_access_r_BITS_ETC__q7[3:0],
	       regs_access_r[0] ? regs_access_r[11:4] : m_r_sckdiv_r[7:0] } ;
  assign m_r_sckdiv_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h0 &&
	     regs_access_r[36] ;

  // register m_r_sckmode_pha_r
  assign m_r_sckmode_pha_r$D_IN =
	     IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d157[0] ;
  assign m_r_sckmode_pha_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h04 &&
	     regs_access_r[36] ;

  // register m_r_sckmode_pol_r
  assign m_r_sckmode_pol_r$D_IN =
	     IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d157[1] ;
  assign m_r_sckmode_pol_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h04 &&
	     regs_access_r[36] ;

  // register m_r_txdata_data_r
  assign m_r_txdata_data_r$D_IN =
	     regs_access_r[0] ? regs_access_r[11:4] : 8'd0 ;
  assign m_r_txdata_data_r$EN = m_r_txdata_data_mod$whas ;

  // register m_r_txmark_r
  assign m_r_txmark_r$D_IN =
	     IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q8[2:0] ;
  assign m_r_txmark_r$EN =
	     EN_regs_access && regs_access_r[44:37] == 8'h50 &&
	     regs_access_r[36] ;

  // register m_rxIn
  assign m_rxIn$D_IN = m_rxIn + 8'd1 ;
  assign m_rxIn$EN =
	     m_st == 3'd3 && m_div == 12'd0 &&
	     m_half_9_AND_NOT_0_CONCAT_m_bitn_8_9_PLUS_4_0__ETC___d102 ;

  // register m_rxOut
  assign m_rxOut$D_IN = m_rxOut + 8'd1 ;
  assign m_rxOut$EN = m_r_rxdata_data_acc$whas && m_rxq$EMPTY_N ;

  // register m_shRx
  assign m_shRx$D_IN =
	     m_r_fmt_endian_r ?
	       { pins_io_i, m_shRx[7:4] } :
	       { m_shRx[3:0], pins_io_i } ;
  assign m_shRx$EN = m_st == 3'd3 && m_div == 12'd0 && !m_half ;

  // register m_shTx
  assign m_shTx$D_IN =
	     MUX_m_bitn$write_1__SEL_1 ?
	       MUX_m_shTx$write_1__VAL_1 :
	       m_txq$D_OUT ;
  assign m_shTx$EN =
	     m_st == 3'd3 && m_div == 12'd0 && m_half &&
	     _0_CONCAT_m_bitn_8_9_PLUS_4_0_ULT_0_CONCAT_IF_m_ETC___d85 ||
	     WILL_FIRE_RL_m_load ;

  // register m_st
  always@(MUX_m_st$write_1__SEL_1 or
	  MUX_m_st$write_1__VAL_1 or
	  MUX_m_dly$write_1__SEL_4 or
	  MUX_m_st$write_1__VAL_2 or
	  WILL_FIRE_RL_m_waited or
	  MUX_m_st$write_1__VAL_3 or WILL_FIRE_RL_m_load)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_m_st$write_1__SEL_1: m_st$D_IN = MUX_m_st$write_1__VAL_1;
      MUX_m_dly$write_1__SEL_4: m_st$D_IN = MUX_m_st$write_1__VAL_2;
      WILL_FIRE_RL_m_waited: m_st$D_IN = MUX_m_st$write_1__VAL_3;
      WILL_FIRE_RL_m_load: m_st$D_IN = 3'd3;
      default: m_st$D_IN = 3'b010 /* unspecified value */ ;
    endcase
  end
  assign m_st$EN =
	     m_st == 3'd0 &&
	     m_csOn_read__3_AND_m_csDrop_port1__read__7_OR__ETC___d36 ||
	     m_st == 3'd3 && m_div == 12'd0 && m_half &&
	     !_0_CONCAT_m_bitn_8_9_PLUS_4_0_ULT_0_CONCAT_IF_m_ETC___d85 ||
	     WILL_FIRE_RL_m_waited ||
	     WILL_FIRE_RL_m_load ;

  // register m_txIn
  assign m_txIn$D_IN = m_txIn + 8'd1 ;
  assign m_txIn$EN = m_txPend && m_txq$FULL_N ;

  // register m_txOut
  assign m_txOut$D_IN = m_txOut + 8'd1 ;
  assign m_txOut$EN = WILL_FIRE_RL_m_load ;

  // register m_txPend
  assign m_txPend$D_IN = m_r_txdata_data_mod$whas ;
  assign m_txPend$EN = 1'd1 ;

  // submodule m_rxq
  assign m_rxq$D_IN = m_shRx ;
  assign m_rxq$ENQ =
	     m_st == 3'd3 && m_div == 12'd0 &&
	     m_half_9_AND_NOT_0_CONCAT_m_bitn_8_9_PLUS_4_0__ETC___d102 ;
  assign m_rxq$DEQ = m_r_rxdata_data_acc$whas && m_rxq$EMPTY_N ;
  assign m_rxq$CLR = 1'b0 ;

  // submodule m_txq
  assign m_txq$D_IN = m_r_txdata_data_r ;
  assign m_txq$ENQ = m_txPend && m_txq$FULL_N ;
  assign m_txq$DEQ = WILL_FIRE_RL_m_load ;
  assign m_txq$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_m_r_fmt_endian_r_THEN_m_shTx_ELSE_0_CONCAT__ETC__q1 =
	     m_r_fmt_endian_r ? m_shTx : { 4'd0, m_shTx[7:4] } ;
  assign IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d157 =
	     regs_access_r[0] ?
	       regs_access_r[11:4] :
	       { 6'd0, m_r_sckmode_pol_r, m_r_sckmode_pha_r } ;
  assign IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d190 =
	     regs_access_r[0] ?
	       regs_access_r[11:4] :
	       { 4'd0, m_r_fmt_dir_r, m_r_fmt_endian_r, m_r_fmt_proto_r } ;
  assign IF_regs_access_r_BIT_0_47_THEN_regs_access_r_B_ETC___d219 =
	     regs_access_r[0] ?
	       regs_access_r[11:4] :
	       { 6'd0, m_r_ie_rxwm_r, m_r_ie_txwm_r } ;
  assign IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q2 =
	     regs_access_r[0] ? regs_access_r[11:4] : { 7'd0, m_r_csdef_r } ;
  assign IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q3 =
	     regs_access_r[0] ? regs_access_r[11:4] : { 7'd0, m_r_csid_r } ;
  assign IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q4 =
	     regs_access_r[0] ? regs_access_r[11:4] : { 6'd0, m_r_csmode_r } ;
  assign IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q6 =
	     regs_access_r[0] ? regs_access_r[11:4] : y__h17630 ;
  assign IF_regs_access_r_BIT_0_THEN_regs_access_r_BITS_ETC__q8 =
	     regs_access_r[0] ? regs_access_r[11:4] : y__h17614 ;
  assign IF_regs_access_r_BIT_1_THEN_regs_access_r_BITS_ETC__q7 =
	     regs_access_r[1] ?
	       regs_access_r[19:12] :
	       { 4'd0, m_r_sckdiv_r[11:8] } ;
  assign IF_regs_access_r_BIT_2_THEN_regs_access_r_BITS_ETC__q5 =
	     regs_access_r[2] ?
	       regs_access_r[27:20] :
	       { 4'd0, m_r_fmt_len_r } ;
  assign NOT_m_r_csid_r_EQ_m_idWas_1_2_3_OR_NOT_m_r_csm_ETC___d22 =
	     m_r_csid_r != m_idWas || m_r_csmode_r != m_modeWas ||
	     x__h2403 & y__h2693 ;
  assign _0_CONCAT_m_bitn_8_9_PLUS_4_0_ULT_0_CONCAT_IF_m_ETC___d85 =
	     nxt__h3484 < { 1'd0, flen__h2185 } ;
  assign _theResult___snd__h17453 = regs_access_r[36] ? 32'd0 : cur__h17451 ;
  assign cur__h10560 =
	     { 8'd0, m_r_delay1_interxfr_r, 8'd0, m_r_delay1_intercs_r } ;
  assign cur__h11702 =
	     { 12'd0,
	       m_r_fmt_len_r,
	       12'd0,
	       m_r_fmt_dir_r,
	       m_r_fmt_endian_r,
	       m_r_fmt_proto_r } ;
  assign cur__h12996 = { x_wget__h644, 31'd0 } ;
  assign cur__h16250 = { 30'd0, m_r_ie_rxwm_r, m_r_ie_txwm_r } ;
  assign cur__h17451 = { 30'd0, x_wget__h1064, x_wget__h993 } ;
  assign cur__h5189 = { 30'd0, m_r_sckmode_pol_r, m_r_sckmode_pha_r } ;
  assign cur__h9423 = { 8'd0, m_r_delay0_sckcs_r, 8'd0, m_r_delay0_cssck_r } ;
  assign flen__h2185 = (m_r_fmt_len_r == 4'd0) ? 4'd8 : m_r_fmt_len_r ;
  assign m_csOn_read__3_AND_m_csDrop_port1__read__7_OR__ETC___d36 =
	     m_csOn &&
	     (m_csDrop$port1__read ||
	      m_r_csmode_r != 2'd2 && m_r_csmode_r != 2'd3) ||
	     m_txq$EMPTY_N ;
  assign m_csOn_read__3_AND_m_csDrop_port1__read__7_OR__ETC___d43 =
	     m_csOn &&
	     (m_csDrop$port1__read ||
	      m_r_csmode_r != 2'd2 && m_r_csmode_r != 2'd3) ||
	     m_txq$EMPTY_N && !m_csOn && m_r_csmode_r != 2'd3 ;
  assign m_half_9_AND_NOT_0_CONCAT_m_bitn_8_9_PLUS_4_0__ETC___d102 =
	     m_half &&
	     !_0_CONCAT_m_bitn_8_9_PLUS_4_0_ULT_0_CONCAT_IF_m_ETC___d85 &&
	     !m_r_fmt_dir_r &&
	     m_rxq$FULL_N ;
  assign nxt__h3484 = { 1'd0, m_bitn } + 5'd4 ;
  assign rd__h14201 = { 29'd0, m_r_txmark_r } ;
  assign rd__h15234 = { 29'd0, m_r_rxmark_r } ;
  assign rd__h4165 = { 20'd0, m_r_sckdiv_r } ;
  assign rd__h6341 = { 31'd0, m_r_csid_r } ;
  assign rd__h7374 = { 31'd0, m_r_csdef_r } ;
  assign rd__h8403 = { 30'd0, m_r_csmode_r } ;
  assign rxLevel__h2182 = m_rxIn - m_rxOut ;
  assign txLevel__h2181 = m_txIn - m_txOut ;
  assign v__h14115 = { x_wget__h786, 23'd0, m_rxq$D_OUT } ;
  assign v__h3824 = txLevel__h2181 < y__h17614 ;
  assign v__h3850 = rxLevel__h2182 > y__h17630 ;
  assign x__h17539 = m_r_sckmode_pol_r ^ m_r_sckmode_pha_r ;
  assign x__h2403 = m_r_csdef_r ^ m_defWas ;
  assign x__h3408 = m_div - 12'd1 ;
  assign x_wget__h1064 = v__h3850 ;
  assign x_wget__h644 = !m_txq$FULL_N ;
  assign x_wget__h786 = !m_rxq$EMPTY_N ;
  assign x_wget__h993 = v__h3824 ;
  assign y__h17614 = { 5'd0, m_r_txmark_r } ;
  assign y__h17630 = { 5'd0, m_r_rxmark_r } ;
  assign y__h2693 = !m_r_csid_r ;
  assign y_avValue_snd__h10558 = regs_access_r[36] ? 32'd0 : cur__h9423 ;
  assign y_avValue_snd__h11691 = regs_access_r[36] ? 32'd0 : cur__h10560 ;
  assign y_avValue_snd__h12994 = regs_access_r[36] ? 32'd0 : cur__h11702 ;
  assign y_avValue_snd__h14096 = regs_access_r[36] ? 32'd0 : cur__h12996 ;
  assign y_avValue_snd__h14186 = regs_access_r[36] ? 32'd0 : v__h14115 ;
  assign y_avValue_snd__h15219 = regs_access_r[36] ? 32'd0 : rd__h14201 ;
  assign y_avValue_snd__h16248 = regs_access_r[36] ? 32'd0 : rd__h15234 ;
  assign y_avValue_snd__h17383 = regs_access_r[36] ? 32'd0 : cur__h16250 ;
  assign y_avValue_snd__h5187 = regs_access_r[36] ? 32'd0 : rd__h4165 ;
  assign y_avValue_snd__h6326 = regs_access_r[36] ? 32'd0 : cur__h5189 ;
  assign y_avValue_snd__h7359 = regs_access_r[36] ? 32'd0 : rd__h6341 ;
  assign y_avValue_snd__h8388 = regs_access_r[36] ? 32'd0 : rd__h7374 ;
  assign y_avValue_snd__h9421 = regs_access_r[36] ? 32'd0 : rd__h8403 ;
  always@(regs_access_r or
	  y_avValue_snd__h5187 or
	  y_avValue_snd__h6326 or
	  y_avValue_snd__h7359 or
	  y_avValue_snd__h8388 or
	  y_avValue_snd__h9421 or
	  y_avValue_snd__h10558 or
	  y_avValue_snd__h11691 or
	  y_avValue_snd__h12994 or
	  y_avValue_snd__h14096 or
	  y_avValue_snd__h14186 or
	  y_avValue_snd__h15219 or
	  y_avValue_snd__h16248 or
	  y_avValue_snd__h17383 or _theResult___snd__h17453)
  begin
    case (regs_access_r[44:37])
      8'h0: y_avValue_rdata__h17448 = y_avValue_snd__h5187;
      8'h04: y_avValue_rdata__h17448 = y_avValue_snd__h6326;
      8'h10: y_avValue_rdata__h17448 = y_avValue_snd__h7359;
      8'h14: y_avValue_rdata__h17448 = y_avValue_snd__h8388;
      8'h18: y_avValue_rdata__h17448 = y_avValue_snd__h9421;
      8'h28: y_avValue_rdata__h17448 = y_avValue_snd__h10558;
      8'h2C: y_avValue_rdata__h17448 = y_avValue_snd__h11691;
      8'h40: y_avValue_rdata__h17448 = y_avValue_snd__h12994;
      8'h48: y_avValue_rdata__h17448 = y_avValue_snd__h14096;
      8'h4C: y_avValue_rdata__h17448 = y_avValue_snd__h14186;
      8'h50: y_avValue_rdata__h17448 = y_avValue_snd__h15219;
      8'h54: y_avValue_rdata__h17448 = y_avValue_snd__h16248;
      8'h70: y_avValue_rdata__h17448 = y_avValue_snd__h17383;
      8'h74: y_avValue_rdata__h17448 = _theResult___snd__h17453;
      default: y_avValue_rdata__h17448 = 32'd0;
    endcase
  end

  // handling of inlined registers

  always@(posedge clk)
  begin
    if (rst_n == `BSV_RESET_VALUE)
      begin
        m_bitn <= `BSV_ASSIGNMENT_DELAY 4'd0;
	m_csAct <= `BSV_ASSIGNMENT_DELAY 1'd1;
	m_csDrop <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_csOn <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_defWas <= `BSV_ASSIGNMENT_DELAY 1'd1;
	m_div <= `BSV_ASSIGNMENT_DELAY 12'd0;
	m_dly <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m_half <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_idWas <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_modeWas <= `BSV_ASSIGNMENT_DELAY 2'd0;
	m_r_csdef_r <= `BSV_ASSIGNMENT_DELAY 1'd1;
	m_r_csid_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_r_csmode_r <= `BSV_ASSIGNMENT_DELAY 2'd0;
	m_r_delay0_cssck_r <= `BSV_ASSIGNMENT_DELAY 8'd1;
	m_r_delay0_sckcs_r <= `BSV_ASSIGNMENT_DELAY 8'd1;
	m_r_delay1_intercs_r <= `BSV_ASSIGNMENT_DELAY 8'd1;
	m_r_delay1_interxfr_r <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m_r_fmt_dir_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_r_fmt_endian_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_r_fmt_len_r <= `BSV_ASSIGNMENT_DELAY 4'd8;
	m_r_fmt_proto_r <= `BSV_ASSIGNMENT_DELAY 2'd0;
	m_r_ie_rxwm_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_r_ie_txwm_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_r_rxmark_r <= `BSV_ASSIGNMENT_DELAY 3'd0;
	m_r_sckdiv_r <= `BSV_ASSIGNMENT_DELAY 12'd3;
	m_r_sckmode_pha_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_r_sckmode_pol_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_r_txdata_data_r <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m_r_txmark_r <= `BSV_ASSIGNMENT_DELAY 3'd0;
	m_rxIn <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m_rxOut <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m_shRx <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m_shTx <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m_st <= `BSV_ASSIGNMENT_DELAY 3'd0;
	m_txIn <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m_txOut <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m_txPend <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (m_bitn$EN) m_bitn <= `BSV_ASSIGNMENT_DELAY m_bitn$D_IN;
	if (m_csAct$EN) m_csAct <= `BSV_ASSIGNMENT_DELAY m_csAct$D_IN;
	if (m_csDrop$EN) m_csDrop <= `BSV_ASSIGNMENT_DELAY m_csDrop$D_IN;
	if (m_csOn$EN) m_csOn <= `BSV_ASSIGNMENT_DELAY m_csOn$D_IN;
	if (m_defWas$EN) m_defWas <= `BSV_ASSIGNMENT_DELAY m_defWas$D_IN;
	if (m_div$EN) m_div <= `BSV_ASSIGNMENT_DELAY m_div$D_IN;
	if (m_dly$EN) m_dly <= `BSV_ASSIGNMENT_DELAY m_dly$D_IN;
	if (m_half$EN) m_half <= `BSV_ASSIGNMENT_DELAY m_half$D_IN;
	if (m_idWas$EN) m_idWas <= `BSV_ASSIGNMENT_DELAY m_idWas$D_IN;
	if (m_modeWas$EN) m_modeWas <= `BSV_ASSIGNMENT_DELAY m_modeWas$D_IN;
	if (m_r_csdef_r$EN)
	  m_r_csdef_r <= `BSV_ASSIGNMENT_DELAY m_r_csdef_r$D_IN;
	if (m_r_csid_r$EN)
	  m_r_csid_r <= `BSV_ASSIGNMENT_DELAY m_r_csid_r$D_IN;
	if (m_r_csmode_r$EN)
	  m_r_csmode_r <= `BSV_ASSIGNMENT_DELAY m_r_csmode_r$D_IN;
	if (m_r_delay0_cssck_r$EN)
	  m_r_delay0_cssck_r <= `BSV_ASSIGNMENT_DELAY m_r_delay0_cssck_r$D_IN;
	if (m_r_delay0_sckcs_r$EN)
	  m_r_delay0_sckcs_r <= `BSV_ASSIGNMENT_DELAY m_r_delay0_sckcs_r$D_IN;
	if (m_r_delay1_intercs_r$EN)
	  m_r_delay1_intercs_r <= `BSV_ASSIGNMENT_DELAY
	      m_r_delay1_intercs_r$D_IN;
	if (m_r_delay1_interxfr_r$EN)
	  m_r_delay1_interxfr_r <= `BSV_ASSIGNMENT_DELAY
	      m_r_delay1_interxfr_r$D_IN;
	if (m_r_fmt_dir_r$EN)
	  m_r_fmt_dir_r <= `BSV_ASSIGNMENT_DELAY m_r_fmt_dir_r$D_IN;
	if (m_r_fmt_endian_r$EN)
	  m_r_fmt_endian_r <= `BSV_ASSIGNMENT_DELAY m_r_fmt_endian_r$D_IN;
	if (m_r_fmt_len_r$EN)
	  m_r_fmt_len_r <= `BSV_ASSIGNMENT_DELAY m_r_fmt_len_r$D_IN;
	if (m_r_fmt_proto_r$EN)
	  m_r_fmt_proto_r <= `BSV_ASSIGNMENT_DELAY m_r_fmt_proto_r$D_IN;
	if (m_r_ie_rxwm_r$EN)
	  m_r_ie_rxwm_r <= `BSV_ASSIGNMENT_DELAY m_r_ie_rxwm_r$D_IN;
	if (m_r_ie_txwm_r$EN)
	  m_r_ie_txwm_r <= `BSV_ASSIGNMENT_DELAY m_r_ie_txwm_r$D_IN;
	if (m_r_rxmark_r$EN)
	  m_r_rxmark_r <= `BSV_ASSIGNMENT_DELAY m_r_rxmark_r$D_IN;
	if (m_r_sckdiv_r$EN)
	  m_r_sckdiv_r <= `BSV_ASSIGNMENT_DELAY m_r_sckdiv_r$D_IN;
	if (m_r_sckmode_pha_r$EN)
	  m_r_sckmode_pha_r <= `BSV_ASSIGNMENT_DELAY m_r_sckmode_pha_r$D_IN;
	if (m_r_sckmode_pol_r$EN)
	  m_r_sckmode_pol_r <= `BSV_ASSIGNMENT_DELAY m_r_sckmode_pol_r$D_IN;
	if (m_r_txdata_data_r$EN)
	  m_r_txdata_data_r <= `BSV_ASSIGNMENT_DELAY m_r_txdata_data_r$D_IN;
	if (m_r_txmark_r$EN)
	  m_r_txmark_r <= `BSV_ASSIGNMENT_DELAY m_r_txmark_r$D_IN;
	if (m_rxIn$EN) m_rxIn <= `BSV_ASSIGNMENT_DELAY m_rxIn$D_IN;
	if (m_rxOut$EN) m_rxOut <= `BSV_ASSIGNMENT_DELAY m_rxOut$D_IN;
	if (m_shRx$EN) m_shRx <= `BSV_ASSIGNMENT_DELAY m_shRx$D_IN;
	if (m_shTx$EN) m_shTx <= `BSV_ASSIGNMENT_DELAY m_shTx$D_IN;
	if (m_st$EN) m_st <= `BSV_ASSIGNMENT_DELAY m_st$D_IN;
	if (m_txIn$EN) m_txIn <= `BSV_ASSIGNMENT_DELAY m_txIn$D_IN;
	if (m_txOut$EN) m_txOut <= `BSV_ASSIGNMENT_DELAY m_txOut$D_IN;
	if (m_txPend$EN) m_txPend <= `BSV_ASSIGNMENT_DELAY m_txPend$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    m_bitn = 4'hA;
    m_csAct = 1'h0;
    m_csDrop = 1'h0;
    m_csOn = 1'h0;
    m_defWas = 1'h0;
    m_div = 12'hAAA;
    m_dly = 8'hAA;
    m_half = 1'h0;
    m_idWas = 1'h0;
    m_modeWas = 2'h2;
    m_r_csdef_r = 1'h0;
    m_r_csid_r = 1'h0;
    m_r_csmode_r = 2'h2;
    m_r_delay0_cssck_r = 8'hAA;
    m_r_delay0_sckcs_r = 8'hAA;
    m_r_delay1_intercs_r = 8'hAA;
    m_r_delay1_interxfr_r = 8'hAA;
    m_r_fmt_dir_r = 1'h0;
    m_r_fmt_endian_r = 1'h0;
    m_r_fmt_len_r = 4'hA;
    m_r_fmt_proto_r = 2'h2;
    m_r_ie_rxwm_r = 1'h0;
    m_r_ie_txwm_r = 1'h0;
    m_r_rxmark_r = 3'h2;
    m_r_sckdiv_r = 12'hAAA;
    m_r_sckmode_pha_r = 1'h0;
    m_r_sckmode_pol_r = 1'h0;
    m_r_txdata_data_r = 8'hAA;
    m_r_txmark_r = 3'h2;
    m_rxIn = 8'hAA;
    m_rxOut = 8'hAA;
    m_shRx = 8'hAA;
    m_shTx = 8'hAA;
    m_st = 3'h2;
    m_txIn = 8'hAA;
    m_txOut = 8'hAA;
    m_txPend = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkSpiBareLines4_8_1_4

