/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Tue Sep 22 00:42:13 JST 2026
 * 
 */

/* Generation options: */
#ifndef __mkSpiRegsTbLines4_h__
#define __mkSpiRegsTbLines4_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkSpiRegsTbLines4 module */
class MOD_mkSpiRegsTbLines4 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_bad;
  MOD_Reg<tUInt8> INST_ph2;
  MOD_Reg<tUInt8> INST_ph3;
  MOD_Reg<tUInt8> INST_r_csdef_r;
  MOD_Reg<tUInt8> INST_r_csid_r;
  MOD_Reg<tUInt8> INST_r_csmode_r;
  MOD_Reg<tUInt8> INST_r_delay0_cssck_r;
  MOD_Reg<tUInt8> INST_r_delay0_sckcs_r;
  MOD_Reg<tUInt8> INST_r_delay1_intercs_r;
  MOD_Reg<tUInt8> INST_r_delay1_interxfr_r;
  MOD_Reg<tUInt8> INST_r_fmt_dir_r;
  MOD_Reg<tUInt8> INST_r_fmt_endian_r;
  MOD_Reg<tUInt8> INST_r_fmt_len_r;
  MOD_Reg<tUInt8> INST_r_fmt_proto_r;
  MOD_Reg<tUInt8> INST_r_ie_rxwm_r;
  MOD_Reg<tUInt8> INST_r_ie_txwm_r;
  MOD_Wire<tUInt8> INST_r_ip_rxwm_r;
  MOD_Wire<tUInt8> INST_r_ip_txwm_r;
  MOD_Wire<tUInt8> INST_r_rxdata_data_acc;
  MOD_Wire<tUInt8> INST_r_rxdata_data_r;
  MOD_Wire<tUInt8> INST_r_rxdata_empty_r;
  MOD_Reg<tUInt8> INST_r_rxmark_r;
  MOD_Reg<tUInt32> INST_r_sckdiv_r;
  MOD_Reg<tUInt8> INST_r_sckmode_pha_r;
  MOD_Reg<tUInt8> INST_r_sckmode_pol_r;
  MOD_Wire<tUInt8> INST_r_txdata_data_mod;
  MOD_Reg<tUInt8> INST_r_txdata_data_r;
  MOD_Wire<tUInt8> INST_r_txdata_full_r;
  MOD_Reg<tUInt8> INST_r_txmark_r;
  MOD_Reg<tUInt32> INST_rstp;
  MOD_Reg<tUInt32> INST_step;
  MOD_Reg<tUInt32> INST_wstp;
 
 /* Constructor */
 public:
  MOD_mkSpiRegsTbLines4(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt8 DEF_x__h24725;
  tUInt8 DEF_x__h24709;
  tUInt8 DEF_x__h24718;
  tUInt8 DEF_x__h24713;
  tUInt32 DEF_y_avValue_rdata__h24746;
  tUInt32 DEF__0_CONCAT_r_fmt_len_r_04___d105;
 
 /* Rules */
 public:
  void RL_run();
  void RL_race();
  void RL_warl();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkSpiRegsTbLines4 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkSpiRegsTbLines4 &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkSpiRegsTbLines4 &backing);
};

#endif /* ifndef __mkSpiRegsTbLines4_h__ */
