/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Tue Sep 22 00:42:13 JST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkSpiRegsTbLines4.h"


/* String declarations */
static std::string const __str_literal_3("FAIL an illegal write at %0h was taken: %08h after %08h read back %08h",
					 70u);
static std::string const __str_literal_1("FAIL ones at %0h: got %08h want %08h", 36u);
static std::string const __str_literal_2("FAIL zeros at %0h: got %08h want %08h", 37u);
static std::string const __str_literal_4("FAILED", 6u);
static std::string const __str_literal_5("PASS all %0d register checks, %0d set-vs-clear races and %0d illegal writes",
					 75u);


/* Constructor */
MOD_mkSpiRegsTbLines4::MOD_mkSpiRegsTbLines4(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_bad(simHdl, "bad", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_ph2(simHdl, "ph2", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_ph3(simHdl, "ph3", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_r_csdef_r(simHdl, "r_csdef_r", this, 1u, (tUInt8)1u, (tUInt8)0u),
    INST_r_csid_r(simHdl, "r_csid_r", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_r_csmode_r(simHdl, "r_csmode_r", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_r_delay0_cssck_r(simHdl, "r_delay0_cssck_r", this, 8u, (tUInt8)1u, (tUInt8)0u),
    INST_r_delay0_sckcs_r(simHdl, "r_delay0_sckcs_r", this, 8u, (tUInt8)1u, (tUInt8)0u),
    INST_r_delay1_intercs_r(simHdl, "r_delay1_intercs_r", this, 8u, (tUInt8)1u, (tUInt8)0u),
    INST_r_delay1_interxfr_r(simHdl, "r_delay1_interxfr_r", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_r_fmt_dir_r(simHdl, "r_fmt_dir_r", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_r_fmt_endian_r(simHdl, "r_fmt_endian_r", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_r_fmt_len_r(simHdl, "r_fmt_len_r", this, 4u, (tUInt8)8u, (tUInt8)0u),
    INST_r_fmt_proto_r(simHdl, "r_fmt_proto_r", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_r_ie_rxwm_r(simHdl, "r_ie_rxwm_r", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_r_ie_txwm_r(simHdl, "r_ie_txwm_r", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_r_ip_rxwm_r(simHdl, "r_ip_rxwm_r", this, 1u, (tUInt8)0u),
    INST_r_ip_txwm_r(simHdl, "r_ip_txwm_r", this, 1u, (tUInt8)0u),
    INST_r_rxdata_data_acc(simHdl, "r_rxdata_data_acc", this, 0u),
    INST_r_rxdata_data_r(simHdl, "r_rxdata_data_r", this, 8u, (tUInt8)0u),
    INST_r_rxdata_empty_r(simHdl, "r_rxdata_empty_r", this, 1u, (tUInt8)0u),
    INST_r_rxmark_r(simHdl, "r_rxmark_r", this, 3u, (tUInt8)0u, (tUInt8)0u),
    INST_r_sckdiv_r(simHdl, "r_sckdiv_r", this, 12u, 3u, (tUInt8)0u),
    INST_r_sckmode_pha_r(simHdl, "r_sckmode_pha_r", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_r_sckmode_pol_r(simHdl, "r_sckmode_pol_r", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_r_txdata_data_mod(simHdl, "r_txdata_data_mod", this, 0u),
    INST_r_txdata_data_r(simHdl, "r_txdata_data_r", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_r_txdata_full_r(simHdl, "r_txdata_full_r", this, 1u, (tUInt8)0u),
    INST_r_txmark_r(simHdl, "r_txmark_r", this, 3u, (tUInt8)0u, (tUInt8)0u),
    INST_rstp(simHdl, "rstp", this, 16u, 0u, (tUInt8)0u),
    INST_step(simHdl, "step", this, 16u, 0u, (tUInt8)0u),
    INST_wstp(simHdl, "wstp", this, 16u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 35u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkSpiRegsTbLines4::init_symbols_0()
{
  init_symbol(&symbols[0u], "bad", SYM_MODULE, &INST_bad);
  init_symbol(&symbols[1u], "ph2", SYM_MODULE, &INST_ph2);
  init_symbol(&symbols[2u], "ph3", SYM_MODULE, &INST_ph3);
  init_symbol(&symbols[3u], "RL_race", SYM_RULE);
  init_symbol(&symbols[4u], "RL_run", SYM_RULE);
  init_symbol(&symbols[5u], "RL_warl", SYM_RULE);
  init_symbol(&symbols[6u], "r_csdef_r", SYM_MODULE, &INST_r_csdef_r);
  init_symbol(&symbols[7u], "r_csid_r", SYM_MODULE, &INST_r_csid_r);
  init_symbol(&symbols[8u], "r_csmode_r", SYM_MODULE, &INST_r_csmode_r);
  init_symbol(&symbols[9u], "r_delay0_cssck_r", SYM_MODULE, &INST_r_delay0_cssck_r);
  init_symbol(&symbols[10u], "r_delay0_sckcs_r", SYM_MODULE, &INST_r_delay0_sckcs_r);
  init_symbol(&symbols[11u], "r_delay1_intercs_r", SYM_MODULE, &INST_r_delay1_intercs_r);
  init_symbol(&symbols[12u], "r_delay1_interxfr_r", SYM_MODULE, &INST_r_delay1_interxfr_r);
  init_symbol(&symbols[13u], "r_fmt_dir_r", SYM_MODULE, &INST_r_fmt_dir_r);
  init_symbol(&symbols[14u], "r_fmt_endian_r", SYM_MODULE, &INST_r_fmt_endian_r);
  init_symbol(&symbols[15u], "r_fmt_len_r", SYM_MODULE, &INST_r_fmt_len_r);
  init_symbol(&symbols[16u], "r_fmt_proto_r", SYM_MODULE, &INST_r_fmt_proto_r);
  init_symbol(&symbols[17u], "r_ie_rxwm_r", SYM_MODULE, &INST_r_ie_rxwm_r);
  init_symbol(&symbols[18u], "r_ie_txwm_r", SYM_MODULE, &INST_r_ie_txwm_r);
  init_symbol(&symbols[19u], "r_ip_rxwm_r", SYM_MODULE, &INST_r_ip_rxwm_r);
  init_symbol(&symbols[20u], "r_ip_txwm_r", SYM_MODULE, &INST_r_ip_txwm_r);
  init_symbol(&symbols[21u], "r_rxdata_data_acc", SYM_MODULE, &INST_r_rxdata_data_acc);
  init_symbol(&symbols[22u], "r_rxdata_data_r", SYM_MODULE, &INST_r_rxdata_data_r);
  init_symbol(&symbols[23u], "r_rxdata_empty_r", SYM_MODULE, &INST_r_rxdata_empty_r);
  init_symbol(&symbols[24u], "r_rxmark_r", SYM_MODULE, &INST_r_rxmark_r);
  init_symbol(&symbols[25u], "r_sckdiv_r", SYM_MODULE, &INST_r_sckdiv_r);
  init_symbol(&symbols[26u], "r_sckmode_pha_r", SYM_MODULE, &INST_r_sckmode_pha_r);
  init_symbol(&symbols[27u], "r_sckmode_pol_r", SYM_MODULE, &INST_r_sckmode_pol_r);
  init_symbol(&symbols[28u], "r_txdata_data_mod", SYM_MODULE, &INST_r_txdata_data_mod);
  init_symbol(&symbols[29u], "r_txdata_data_r", SYM_MODULE, &INST_r_txdata_data_r);
  init_symbol(&symbols[30u], "r_txdata_full_r", SYM_MODULE, &INST_r_txdata_full_r);
  init_symbol(&symbols[31u], "r_txmark_r", SYM_MODULE, &INST_r_txmark_r);
  init_symbol(&symbols[32u], "rstp", SYM_MODULE, &INST_rstp);
  init_symbol(&symbols[33u], "step", SYM_MODULE, &INST_step);
  init_symbol(&symbols[34u], "wstp", SYM_MODULE, &INST_wstp);
}


/* Rule actions */

void MOD_mkSpiRegsTbLines4::RL_run()
{
  tUInt32 DEF_x__h24365;
  tUInt8 DEF_NOT_0_CONCAT_step_BITS_15_TO_2_ULT_14___d192;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d53;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d50;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d55;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d57;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d59;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d62;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d65;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d67;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d69;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d71;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d74;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d76;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_NOT_step_ETC___d86;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d173;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_NOT_step_ETC___d172;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d188;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6;
  tUInt8 DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_NOT_step_ETC___d190;
  tUInt8 DEF_NOT_step_BITS_1_TO_0_EQ_2___d81;
  tUInt8 DEF_NOT_step_BITS_1_TO_0_EQ_1_8___d80;
  tUInt8 DEF_NOT_step_BITS_1_TO_0_EQ_0___d77;
  tUInt8 DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10;
  tUInt8 DEF_NOT_step_BITS_1_TO_0_EQ_1_8_0_AND_NOT_step_BIT_ETC___d169;
  tUInt8 DEF_step_BITS_1_TO_0_EQ_1_8_AND_NOT_IF_NOT_step_BI_ETC___d165;
  tUInt32 DEF_n__h1379;
  tUInt8 DEF_x__h12674;
  tUInt8 DEF_x__h12593;
  tUInt8 DEF_x__h12901;
  tUInt8 DEF_x__h12912;
  tUInt8 DEF_step_BITS_1_TO_0_EQ_1___d78;
  tUInt8 DEF_step_BITS_1_TO_0_EQ_2___d9;
  tUInt8 DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_3_ELSE_0___d60;
  tUInt8 DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_7_ELSE_0___d72;
  tUInt8 DEF_off__h1508;
  tUInt8 DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_255_ELSE_0___d63;
  tUInt8 DEF_x__h12664;
  tUInt8 DEF_step_BITS_1_TO_0_EQ_0___d8;
  tUInt32 DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_4095_ELSE_0___d51;
  tUInt32 DEF__theResult___snd__h12886;
  tUInt32 DEF_IF_step_BITS_15_TO_2_EQ_13_1_THEN_0x0_ELSE_IF__ETC___d162;
  tUInt32 DEF_y_avValue_snd__h24179;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_12___d13;
  tUInt32 DEF_y_avValue_snd__h24177;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_11___d15;
  tUInt32 DEF_y_avValue_snd__h24175;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_10___d17;
  tUInt32 DEF_y_avValue_snd__h12825;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_9___d19;
  tUInt32 DEF_y_avValue_snd__h12823;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_8___d21;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_7___d23;
  tUInt32 DEF_y_avValue_snd__h24167;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_6___d25;
  tUInt32 DEF_y_avValue_snd__h24165;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_5___d27;
  tUInt32 DEF_y_avValue_snd__h24163;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_4___d29;
  tUInt32 DEF_y_avValue_snd__h24161;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_3___d31;
  tUInt32 DEF_y_avValue_snd__h24159;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_2___d33;
  tUInt32 DEF_y_avValue_snd__h24157;
  tUInt8 DEF_step_BITS_15_TO_2_EQ_1___d35;
  tUInt32 DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148;
  tUInt32 DEF_y_avValue_snd__h24155;
  tUInt8 DEF_NOT_step_BITS_15_TO_2_EQ_13_1_2_AND_NOT_step_B_ETC___d48;
  tUInt32 DEF_y_avValue_rdata__h12864;
  tUInt32 DEF_step_BITS_15_TO_2___h1400;
  tUInt8 DEF_x__h23709;
  tUInt8 DEF_x__h23713;
  tUInt8 DEF_x__h23735;
  tUInt8 DEF_x__h23754;
  tUInt8 DEF_x_wget__h628;
  tUInt8 DEF_x_wget__h770;
  tUInt8 DEF_x__h24111;
  tUInt8 DEF_x__h24115;
  tUInt8 DEF_x_wget__h977;
  tUInt8 DEF_x_wget__h1048;
  tUInt8 DEF_x__h23773;
  tUInt8 DEF_x__h24057;
  tUInt8 DEF_x__h24076;
  tUInt8 DEF_x__h23808;
  tUInt8 DEF_x__h23812;
  tUInt8 DEF_x__h23851;
  tUInt8 DEF_x__h23855;
  tUInt8 DEF_x_wget__h699;
  tUInt32 DEF_x__h23674;
  tUInt32 DEF_x__h24384;
  tUInt8 DEF_ph__h1380;
  DEF_x__h24384 = INST_step.METH_read();
  DEF_ph__h1380 = (tUInt8)((tUInt8)3u & DEF_x__h24384);
  DEF_x__h23674 = INST_r_sckdiv_r.METH_read();
  DEF_x_wget__h699 = INST_r_rxdata_data_r.METH_wget();
  DEF_x__h23855 = INST_r_delay1_interxfr_r.METH_read();
  DEF_x__h23851 = INST_r_delay1_intercs_r.METH_read();
  DEF_x__h23812 = INST_r_delay0_sckcs_r.METH_read();
  DEF_x__h23808 = INST_r_delay0_cssck_r.METH_read();
  DEF_x__h24725 = INST_r_fmt_len_r.METH_read();
  DEF_x__h24076 = INST_r_rxmark_r.METH_read();
  DEF_x__h24057 = INST_r_txmark_r.METH_read();
  DEF_x__h24709 = INST_r_fmt_proto_r.METH_read();
  DEF_x__h23773 = INST_r_csmode_r.METH_read();
  DEF_x_wget__h1048 = INST_r_ip_rxwm_r.METH_wget();
  DEF_x_wget__h977 = INST_r_ip_txwm_r.METH_wget();
  DEF_x__h24115 = INST_r_ie_rxwm_r.METH_read();
  DEF_x__h24111 = INST_r_ie_txwm_r.METH_read();
  DEF_x_wget__h770 = INST_r_rxdata_empty_r.METH_wget();
  DEF_x_wget__h628 = INST_r_txdata_full_r.METH_wget();
  DEF_x__h24718 = INST_r_fmt_dir_r.METH_read();
  DEF_x__h24713 = INST_r_fmt_endian_r.METH_read();
  DEF_x__h23754 = INST_r_csdef_r.METH_read();
  DEF_x__h23735 = INST_r_csid_r.METH_read();
  DEF_x__h23713 = INST_r_sckmode_pol_r.METH_read();
  DEF_x__h23709 = INST_r_sckmode_pha_r.METH_read();
  DEF_step_BITS_15_TO_2___h1400 = (tUInt32)(DEF_x__h24384 >> 2u);
  DEF_y_avValue_snd__h24155 = DEF_x__h23674;
  DEF_step_BITS_15_TO_2_EQ_1___d35 = DEF_step_BITS_15_TO_2___h1400 == 1u;
  DEF_y_avValue_snd__h24157 = (((tUInt32)(DEF_x__h23713)) << 1u) | (tUInt32)(DEF_x__h23709);
  DEF_step_BITS_15_TO_2_EQ_2___d33 = DEF_step_BITS_15_TO_2___h1400 == 2u;
  DEF_y_avValue_snd__h24159 = (tUInt32)(DEF_x__h23735);
  DEF_step_BITS_15_TO_2_EQ_3___d31 = DEF_step_BITS_15_TO_2___h1400 == 3u;
  DEF_y_avValue_snd__h24161 = (tUInt32)(DEF_x__h23754);
  DEF_step_BITS_15_TO_2_EQ_4___d29 = DEF_step_BITS_15_TO_2___h1400 == 4u;
  DEF_y_avValue_snd__h24163 = (tUInt32)(DEF_x__h23773);
  DEF_step_BITS_15_TO_2_EQ_5___d27 = DEF_step_BITS_15_TO_2___h1400 == 5u;
  DEF_y_avValue_snd__h24165 = (((((tUInt32)((tUInt8)0u)) << 24u) | (((tUInt32)(DEF_x__h23812)) << 16u)) | (((tUInt32)((tUInt8)0u)) << 8u)) | (tUInt32)(DEF_x__h23808);
  DEF_step_BITS_15_TO_2_EQ_6___d25 = DEF_step_BITS_15_TO_2___h1400 == 6u;
  DEF_y_avValue_snd__h24167 = (((((tUInt32)((tUInt8)0u)) << 24u) | (((tUInt32)(DEF_x__h23855)) << 16u)) | (((tUInt32)((tUInt8)0u)) << 8u)) | (tUInt32)(DEF_x__h23851);
  DEF_step_BITS_15_TO_2_EQ_7___d23 = DEF_step_BITS_15_TO_2___h1400 == 7u;
  DEF_step_BITS_15_TO_2_EQ_8___d21 = DEF_step_BITS_15_TO_2___h1400 == 8u;
  DEF_step_BITS_15_TO_2_EQ_9___d19 = DEF_step_BITS_15_TO_2___h1400 == 9u;
  DEF_step_BITS_15_TO_2_EQ_10___d17 = DEF_step_BITS_15_TO_2___h1400 == 10u;
  DEF_y_avValue_snd__h24175 = (tUInt32)(DEF_x__h24057);
  DEF_step_BITS_15_TO_2_EQ_11___d15 = DEF_step_BITS_15_TO_2___h1400 == 11u;
  DEF_step_BITS_1_TO_0_EQ_0___d8 = DEF_ph__h1380 == (tUInt8)0u;
  DEF_y_avValue_snd__h24177 = (tUInt32)(DEF_x__h24076);
  DEF_step_BITS_15_TO_2_EQ_12___d13 = DEF_step_BITS_15_TO_2___h1400 == 12u;
  DEF_NOT_step_BITS_15_TO_2_EQ_13_1_2_AND_NOT_step_B_ETC___d48 = !(DEF_step_BITS_15_TO_2___h1400 == 13u) && (!DEF_step_BITS_15_TO_2_EQ_12___d13 && (!DEF_step_BITS_15_TO_2_EQ_11___d15 && (!DEF_step_BITS_15_TO_2_EQ_10___d17 && (!DEF_step_BITS_15_TO_2_EQ_9___d19 && (!DEF_step_BITS_15_TO_2_EQ_8___d21 && (!DEF_step_BITS_15_TO_2_EQ_7___d23 && (!DEF_step_BITS_15_TO_2_EQ_6___d25 && (!DEF_step_BITS_15_TO_2_EQ_5___d27 && (!DEF_step_BITS_15_TO_2_EQ_4___d29 && (!DEF_step_BITS_15_TO_2_EQ_3___d31 && (!DEF_step_BITS_15_TO_2_EQ_2___d33 && !DEF_step_BITS_15_TO_2_EQ_1___d35)))))))))));
  DEF_y_avValue_snd__h24179 = (((tUInt32)(DEF_x__h24115)) << 1u) | (tUInt32)(DEF_x__h24111);
  switch (DEF_step_BITS_15_TO_2___h1400) {
  case 8u:
  case 9u:
  case 13u:
    DEF_IF_step_BITS_15_TO_2_EQ_13_1_THEN_0x0_ELSE_IF__ETC___d162 = 0u;
    break;
  case 1u:
  case 4u:
  case 12u:
    DEF_IF_step_BITS_15_TO_2_EQ_13_1_THEN_0x0_ELSE_IF__ETC___d162 = 3u;
    break;
  case 10u:
  case 11u:
    DEF_IF_step_BITS_15_TO_2_EQ_13_1_THEN_0x0_ELSE_IF__ETC___d162 = 7u;
    break;
  case 7u:
    DEF_IF_step_BITS_15_TO_2_EQ_13_1_THEN_0x0_ELSE_IF__ETC___d162 = 524303u;
    break;
  case 5u:
  case 6u:
    DEF_IF_step_BITS_15_TO_2_EQ_13_1_THEN_0x0_ELSE_IF__ETC___d162 = 16711935u;
    break;
  case 2u:
  case 3u:
    DEF_IF_step_BITS_15_TO_2_EQ_13_1_THEN_0x0_ELSE_IF__ETC___d162 = 1u;
    break;
  default:
    DEF_IF_step_BITS_15_TO_2_EQ_13_1_THEN_0x0_ELSE_IF__ETC___d162 = 4095u;
  }
  DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_4095_ELSE_0___d51 = DEF_step_BITS_1_TO_0_EQ_0___d8 ? 4095u : 0u;
  DEF_x__h12664 = INST_r_rxdata_data_r.METH_whas() ? DEF_x_wget__h699 : (tUInt8)0u;
  DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_255_ELSE_0___d63 = DEF_step_BITS_1_TO_0_EQ_0___d8 ? (tUInt8)255u : (tUInt8)0u;
  DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_7_ELSE_0___d72 = DEF_step_BITS_1_TO_0_EQ_0___d8 ? (tUInt8)7u : (tUInt8)0u;
  switch (DEF_step_BITS_15_TO_2___h1400) {
  case 13u:
    DEF_off__h1508 = (tUInt8)116u;
    break;
  case 12u:
    DEF_off__h1508 = (tUInt8)112u;
    break;
  case 11u:
    DEF_off__h1508 = (tUInt8)84u;
    break;
  case 10u:
    DEF_off__h1508 = (tUInt8)80u;
    break;
  case 9u:
    DEF_off__h1508 = (tUInt8)76u;
    break;
  case 8u:
    DEF_off__h1508 = (tUInt8)72u;
    break;
  case 7u:
    DEF_off__h1508 = (tUInt8)64u;
    break;
  case 6u:
    DEF_off__h1508 = (tUInt8)44u;
    break;
  case 5u:
    DEF_off__h1508 = (tUInt8)40u;
    break;
  case 4u:
    DEF_off__h1508 = (tUInt8)24u;
    break;
  case 3u:
    DEF_off__h1508 = (tUInt8)20u;
    break;
  case 2u:
    DEF_off__h1508 = (tUInt8)16u;
    break;
  case 1u:
    DEF_off__h1508 = (tUInt8)4u;
    break;
  default:
    DEF_off__h1508 = (tUInt8)0u;
  }
  DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_3_ELSE_0___d60 = DEF_step_BITS_1_TO_0_EQ_0___d8 ? (tUInt8)3u : (tUInt8)0u;
  DEF__0_CONCAT_r_fmt_len_r_04___d105 = 65535u & ((tUInt32)(DEF_x__h24725));
  DEF_y_avValue_rdata__h24746 = (((DEF__0_CONCAT_r_fmt_len_r_04___d105 << 16u) | (((tUInt32)(DEF_x__h24718)) << 3u)) | (((tUInt32)(DEF_x__h24713)) << 2u)) | (tUInt32)(DEF_x__h24709);
  DEF_step_BITS_1_TO_0_EQ_2___d9 = DEF_ph__h1380 == (tUInt8)2u;
  DEF_step_BITS_1_TO_0_EQ_1___d78 = DEF_ph__h1380 == (tUInt8)1u;
  DEF_x__h12912 = INST_r_ip_rxwm_r.METH_whas() && DEF_x_wget__h1048;
  DEF_x__h12901 = INST_r_ip_txwm_r.METH_whas() && DEF_x_wget__h977;
  DEF__theResult___snd__h12886 = (((tUInt32)(DEF_x__h12912)) << 1u) | (tUInt32)(DEF_x__h12901);
  DEF_x__h12593 = INST_r_txdata_full_r.METH_whas() && DEF_x_wget__h628;
  DEF_y_avValue_snd__h12823 = ((tUInt32)(DEF_x__h12593)) << 31u;
  DEF_x__h12674 = INST_r_rxdata_empty_r.METH_whas() && DEF_x_wget__h770;
  DEF_y_avValue_snd__h12825 = (((tUInt32)(DEF_x__h12674)) << 31u) | (tUInt32)(DEF_x__h12664);
  switch (DEF_step_BITS_15_TO_2___h1400) {
  case 1u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_snd__h24157;
    break;
  case 2u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_snd__h24159;
    break;
  case 3u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_snd__h24161;
    break;
  case 4u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_snd__h24163;
    break;
  case 5u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_snd__h24165;
    break;
  case 6u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_snd__h24167;
    break;
  case 7u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_rdata__h24746;
    break;
  case 8u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_snd__h12823;
    break;
  case 9u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_snd__h12825;
    break;
  case 10u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_snd__h24175;
    break;
  case 11u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_snd__h24177;
    break;
  case 12u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF_y_avValue_snd__h24179;
    break;
  case 13u:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = DEF__theResult___snd__h12886;
    break;
  default:
    DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148 = 0u;
  }
  DEF_y_avValue_rdata__h12864 = DEF_NOT_step_BITS_15_TO_2_EQ_13_1_2_AND_NOT_step_B_ETC___d48 ? DEF_y_avValue_snd__h24155 : DEF_IF_step_BITS_15_TO_2_EQ_1_5_THEN_0_CONCAT_r_sc_ETC___d148;
  DEF_n__h1379 = 65535u & ((((tUInt32)((tUInt8)0u)) << 14u) | DEF_step_BITS_15_TO_2___h1400);
  DEF_step_BITS_1_TO_0_EQ_1_8_AND_NOT_IF_NOT_step_BI_ETC___d165 = DEF_step_BITS_1_TO_0_EQ_1___d78 && !(DEF_y_avValue_rdata__h12864 == DEF_IF_step_BITS_15_TO_2_EQ_13_1_THEN_0x0_ELSE_IF__ETC___d162);
  DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 = DEF_step_BITS_1_TO_0_EQ_0___d8 || DEF_step_BITS_1_TO_0_EQ_2___d9;
  DEF_NOT_step_BITS_1_TO_0_EQ_0___d77 = !DEF_step_BITS_1_TO_0_EQ_0___d8;
  DEF_NOT_step_BITS_1_TO_0_EQ_1_8___d80 = !DEF_step_BITS_1_TO_0_EQ_1___d78;
  DEF_NOT_step_BITS_1_TO_0_EQ_2___d81 = !DEF_step_BITS_1_TO_0_EQ_2___d9;
  DEF_NOT_step_BITS_1_TO_0_EQ_1_8_0_AND_NOT_step_BIT_ETC___d169 = DEF_NOT_step_BITS_1_TO_0_EQ_1_8___d80 && (DEF_NOT_step_BITS_1_TO_0_EQ_2___d81 && !(DEF_y_avValue_rdata__h12864 == 0u));
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 = DEF_n__h1379 < 14u;
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_NOT_step_ETC___d190 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_NOT_step_BITS_1_TO_0_EQ_0___d77 && DEF_NOT_step_BITS_1_TO_0_EQ_1_8_0_AND_NOT_step_BIT_ETC___d169);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d188 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_2___d9 && DEF_step_BITS_15_TO_2_EQ_7___d23);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_NOT_step_ETC___d172 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_NOT_step_BITS_1_TO_0_EQ_0___d77 && (DEF_step_BITS_1_TO_0_EQ_1_8_AND_NOT_IF_NOT_step_BI_ETC___d165 || DEF_NOT_step_BITS_1_TO_0_EQ_1_8_0_AND_NOT_step_BIT_ETC___d169));
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d173 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && DEF_step_BITS_1_TO_0_EQ_1_8_AND_NOT_IF_NOT_step_BI_ETC___d165;
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_NOT_step_ETC___d86 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_NOT_step_BITS_1_TO_0_EQ_0___d77 && ((DEF_step_BITS_1_TO_0_EQ_1___d78 && DEF_step_BITS_15_TO_2_EQ_9___d19) || (DEF_NOT_step_BITS_1_TO_0_EQ_1_8___d80 && (DEF_NOT_step_BITS_1_TO_0_EQ_2___d81 && DEF_step_BITS_15_TO_2_EQ_9___d19))));
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d76 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_step_BITS_15_TO_2_EQ_12___d13);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d74 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_step_BITS_15_TO_2_EQ_11___d15);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d71 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_step_BITS_15_TO_2_EQ_10___d17);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d69 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_step_BITS_15_TO_2_EQ_8___d21);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d67 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_step_BITS_15_TO_2_EQ_7___d23);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d65 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_step_BITS_15_TO_2_EQ_6___d25);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d62 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_step_BITS_15_TO_2_EQ_5___d27);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d59 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_step_BITS_15_TO_2_EQ_4___d29);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d55 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_step_BITS_15_TO_2_EQ_2___d33);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d57 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_step_BITS_15_TO_2_EQ_3___d31);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d50 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_NOT_step_BITS_15_TO_2_EQ_13_1_2_AND_NOT_step_B_ETC___d48);
  DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d53 = DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6 && (DEF_step_BITS_1_TO_0_EQ_0_OR_step_BITS_1_TO_0_EQ_2___d10 && DEF_step_BITS_15_TO_2_EQ_1___d35);
  DEF_NOT_0_CONCAT_step_BITS_15_TO_2_ULT_14___d192 = !DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6;
  DEF_x__h24365 = 65535u & (DEF_x__h24384 + 1u);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d50)
    INST_r_sckdiv_r.METH_write(DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_4095_ELSE_0___d51);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d53)
    INST_r_sckmode_pha_r.METH_write(DEF_step_BITS_1_TO_0_EQ_0___d8);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d53)
    INST_r_sckmode_pol_r.METH_write(DEF_step_BITS_1_TO_0_EQ_0___d8);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d55)
    INST_r_csid_r.METH_write(DEF_step_BITS_1_TO_0_EQ_0___d8);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d57)
    INST_r_csdef_r.METH_write(DEF_step_BITS_1_TO_0_EQ_0___d8);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d59)
    INST_r_csmode_r.METH_write(DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_3_ELSE_0___d60);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d62)
    INST_r_delay0_cssck_r.METH_write(DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_255_ELSE_0___d63);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d62)
    INST_r_delay0_sckcs_r.METH_write(DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_255_ELSE_0___d63);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d65)
    INST_r_delay1_intercs_r.METH_write(DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_255_ELSE_0___d63);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d67)
    INST_r_fmt_proto_r.METH_write(DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_3_ELSE_0___d60);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d65)
    INST_r_delay1_interxfr_r.METH_write(DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_255_ELSE_0___d63);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d67)
    INST_r_fmt_endian_r.METH_write(DEF_step_BITS_1_TO_0_EQ_0___d8);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d67)
    INST_r_fmt_dir_r.METH_write(DEF_step_BITS_1_TO_0_EQ_0___d8);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d69)
    INST_r_txdata_data_r.METH_write(DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_255_ELSE_0___d63);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d69)
    INST_r_txdata_data_mod.METH_wset();
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d71)
    INST_r_txmark_r.METH_write(DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_7_ELSE_0___d72);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d74)
    INST_r_rxmark_r.METH_write(DEF_IF_step_BITS_1_TO_0_EQ_0_THEN_7_ELSE_0___d72);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d76)
    INST_r_ie_txwm_r.METH_write(DEF_step_BITS_1_TO_0_EQ_0___d8);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d76)
    INST_r_ie_rxwm_r.METH_write(DEF_step_BITS_1_TO_0_EQ_0___d8);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_NOT_step_ETC___d86)
    INST_r_rxdata_data_acc.METH_wset();
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_NOT_step_ETC___d172)
    INST_bad.METH_write((tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d173)
      dollar_display(sim_hdl,
		     this,
		     "s,8,32,32",
		     &__str_literal_1,
		     DEF_off__h1508,
		     DEF_y_avValue_rdata__h12864,
		     DEF_IF_step_BITS_15_TO_2_EQ_13_1_THEN_0x0_ELSE_IF__ETC___d162);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_step_BIT_ETC___d188)
    INST_r_fmt_len_r.METH_write((tUInt8)0u);
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14_AND_NOT_step_ETC___d190)
      dollar_display(sim_hdl,
		     this,
		     "s,8,32,32",
		     &__str_literal_2,
		     DEF_off__h1508,
		     DEF_y_avValue_rdata__h12864,
		     0u);
  if (DEF__0_CONCAT_step_BITS_15_TO_2_ULT_14___d6)
    INST_step.METH_write(DEF_x__h24365);
  if (DEF_NOT_0_CONCAT_step_BITS_15_TO_2_ULT_14___d192)
    INST_ph2.METH_write((tUInt8)1u);
}

void MOD_mkSpiRegsTbLines4::RL_race()
{
  INST_ph3.METH_write((tUInt8)1u);
}

void MOD_mkSpiRegsTbLines4::RL_warl()
{
  tUInt32 DEF_x__h25974;
  tUInt8 DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_wstp_96_REM_3_99_ETC___d204;
  tUInt8 DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_NOT_wstp_96_REM__ETC___d206;
  tUInt8 DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_NOT_wstp_96_REM__ETC___d215;
  tUInt8 DEF_NOT_wstp_96_REM_3_99_EQ_2_00___d205;
  tUInt8 DEF_NOT_wstp_96_QUOT_3_97_EQ_0_98_17_AND_bad_18___d219;
  tUInt8 DEF_NOT_wstp_96_QUOT_3_97_EQ_0_98___d217;
  tUInt8 DEF_NOT_wstp_96_QUOT_3_97_EQ_0_98_17_AND_NOT_bad_1_ETC___d221;
  tUInt32 DEF__0_CONCAT_IF_bad_18_THEN_1_ELSE_0_25___d226;
  tUInt32 DEF_p__h24452;
  tUInt8 DEF_wstp_96_REM_3_99_EQ_2___d200;
  tUInt8 DEF_wstp_96_QUOT_3_97_EQ_0___d198;
  tUInt8 DEF_code__h24560;
  tUInt8 DEF_x__h25771;
  tUInt8 DEF_x__h25822;
  tUInt8 DEF_x__h24971;
  tUInt32 DEF_IF_wstp_96_REM_3_99_EQ_0_07_THEN_0x80000_ELSE__ETC___d208;
  tUInt8 DEF_IF_wstp_96_REM_3_99_EQ_0_07_THEN_0x80000_ELSE__ETC___d212;
  tUInt8 DEF_bad__h24487;
  tUInt32 DEF_x__h25978;
  tUInt32 DEF_signed_0___d223;
  tUInt32 DEF_signed_1___d224;
  tUInt32 DEF_signed_14___d222;
  DEF_signed_14___d222 = 14u;
  DEF_signed_1___d224 = 1u;
  DEF_signed_0___d223 = 0u;
  DEF_x__h25978 = INST_wstp.METH_read();
  DEF_x__h24725 = INST_r_fmt_len_r.METH_read();
  DEF_x__h24709 = INST_r_fmt_proto_r.METH_read();
  DEF_x__h24718 = INST_r_fmt_dir_r.METH_read();
  DEF_x__h24713 = INST_r_fmt_endian_r.METH_read();
  DEF_bad__h24487 = INST_bad.METH_read();
  DEF_code__h24560 = DEF_bad__h24487 ? (tUInt8)1u : (tUInt8)0u;
  DEF_wstp_96_QUOT_3_97_EQ_0___d198 = (65535u & (DEF_x__h25978 / 3u)) == 0u;
  DEF_p__h24452 = 65535u & (DEF_x__h25978 % 3u);
  DEF_IF_wstp_96_REM_3_99_EQ_0_07_THEN_0x80000_ELSE__ETC___d208 = DEF_p__h24452 == 0u ? 524288u : 589824u;
  DEF_IF_wstp_96_REM_3_99_EQ_0_07_THEN_0x80000_ELSE__ETC___d212 = (tUInt8)((tUInt8)15u & (DEF_IF_wstp_96_REM_3_99_EQ_0_07_THEN_0x80000_ELSE__ETC___d208 >> 16u));
  DEF_x__h24971 = (tUInt8)((tUInt8)3u & DEF_IF_wstp_96_REM_3_99_EQ_0_07_THEN_0x80000_ELSE__ETC___d208);
  DEF_x__h25822 = (tUInt8)((tUInt8)1u & (DEF_IF_wstp_96_REM_3_99_EQ_0_07_THEN_0x80000_ELSE__ETC___d208 >> 3u));
  DEF_x__h25771 = (tUInt8)((tUInt8)1u & (DEF_IF_wstp_96_REM_3_99_EQ_0_07_THEN_0x80000_ELSE__ETC___d208 >> 2u));
  DEF_wstp_96_REM_3_99_EQ_2___d200 = DEF_p__h24452 == 2u;
  DEF__0_CONCAT_r_fmt_len_r_04___d105 = 65535u & ((tUInt32)(DEF_x__h24725));
  DEF_y_avValue_rdata__h24746 = (((DEF__0_CONCAT_r_fmt_len_r_04___d105 << 16u) | (((tUInt32)(DEF_x__h24718)) << 3u)) | (((tUInt32)(DEF_x__h24713)) << 2u)) | (tUInt32)(DEF_x__h24709);
  DEF__0_CONCAT_IF_bad_18_THEN_1_ELSE_0_25___d226 = (tUInt32)(DEF_code__h24560);
  DEF_NOT_wstp_96_QUOT_3_97_EQ_0_98___d217 = !DEF_wstp_96_QUOT_3_97_EQ_0___d198;
  DEF_NOT_wstp_96_QUOT_3_97_EQ_0_98_17_AND_NOT_bad_1_ETC___d221 = DEF_NOT_wstp_96_QUOT_3_97_EQ_0_98___d217 && !DEF_bad__h24487;
  DEF_NOT_wstp_96_QUOT_3_97_EQ_0_98_17_AND_bad_18___d219 = DEF_NOT_wstp_96_QUOT_3_97_EQ_0_98___d217 && DEF_bad__h24487;
  DEF_NOT_wstp_96_REM_3_99_EQ_2_00___d205 = !DEF_wstp_96_REM_3_99_EQ_2___d200;
  DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_NOT_wstp_96_REM__ETC___d215 = DEF_wstp_96_QUOT_3_97_EQ_0___d198 && (DEF_NOT_wstp_96_REM_3_99_EQ_2_00___d205 && DEF_IF_wstp_96_REM_3_99_EQ_0_07_THEN_0x80000_ELSE__ETC___d212 <= (tUInt8)8u);
  DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_NOT_wstp_96_REM__ETC___d206 = DEF_wstp_96_QUOT_3_97_EQ_0___d198 && DEF_NOT_wstp_96_REM_3_99_EQ_2_00___d205;
  DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_wstp_96_REM_3_99_ETC___d204 = DEF_wstp_96_QUOT_3_97_EQ_0___d198 && (DEF_wstp_96_REM_3_99_EQ_2___d200 && !(DEF__0_CONCAT_r_fmt_len_r_04___d105 == 8u));
  DEF_x__h25974 = 65535u & (DEF_x__h25978 + 1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_wstp_96_REM_3_99_ETC___d204)
      dollar_display(sim_hdl,
		     this,
		     "s,8,32,32,32",
		     &__str_literal_3,
		     (tUInt8)64u,
		     589824u,
		     524288u,
		     DEF_y_avValue_rdata__h24746);
  if (DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_wstp_96_REM_3_99_ETC___d204)
    INST_bad.METH_write((tUInt8)1u);
  if (DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_NOT_wstp_96_REM__ETC___d206)
    INST_r_fmt_endian_r.METH_write(DEF_x__h25771);
  if (DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_NOT_wstp_96_REM__ETC___d206)
    INST_r_fmt_proto_r.METH_write(DEF_x__h24971);
  if (DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_NOT_wstp_96_REM__ETC___d206)
    INST_r_fmt_dir_r.METH_write(DEF_x__h25822);
  if (DEF_wstp_96_QUOT_3_97_EQ_0_98_AND_NOT_wstp_96_REM__ETC___d215)
    INST_r_fmt_len_r.METH_write(DEF_IF_wstp_96_REM_3_99_EQ_0_07_THEN_0x80000_ELSE__ETC___d212);
  if (DEF_wstp_96_QUOT_3_97_EQ_0___d198)
    INST_wstp.METH_write(DEF_x__h25974);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_NOT_wstp_96_QUOT_3_97_EQ_0_98_17_AND_bad_18___d219)
      dollar_display(sim_hdl, this, "s", &__str_literal_4);
    if (DEF_NOT_wstp_96_QUOT_3_97_EQ_0_98_17_AND_NOT_bad_1_ETC___d221)
      dollar_display(sim_hdl,
		     this,
		     "s,-32,-32,-32",
		     &__str_literal_5,
		     DEF_signed_14___d222,
		     DEF_signed_0___d223,
		     DEF_signed_1___d224);
    if (DEF_NOT_wstp_96_QUOT_3_97_EQ_0_98___d217)
      dollar_finish(sim_hdl, "32", DEF__0_CONCAT_IF_bad_18_THEN_1_ELSE_0_25___d226);
  }
}


/* Methods */


/* Reset routines */

void MOD_mkSpiRegsTbLines4::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_wstp.reset_RST(ARG_rst_in);
  INST_step.reset_RST(ARG_rst_in);
  INST_rstp.reset_RST(ARG_rst_in);
  INST_r_txmark_r.reset_RST(ARG_rst_in);
  INST_r_txdata_data_r.reset_RST(ARG_rst_in);
  INST_r_sckmode_pol_r.reset_RST(ARG_rst_in);
  INST_r_sckmode_pha_r.reset_RST(ARG_rst_in);
  INST_r_sckdiv_r.reset_RST(ARG_rst_in);
  INST_r_rxmark_r.reset_RST(ARG_rst_in);
  INST_r_ie_txwm_r.reset_RST(ARG_rst_in);
  INST_r_ie_rxwm_r.reset_RST(ARG_rst_in);
  INST_r_fmt_proto_r.reset_RST(ARG_rst_in);
  INST_r_fmt_len_r.reset_RST(ARG_rst_in);
  INST_r_fmt_endian_r.reset_RST(ARG_rst_in);
  INST_r_fmt_dir_r.reset_RST(ARG_rst_in);
  INST_r_delay1_interxfr_r.reset_RST(ARG_rst_in);
  INST_r_delay1_intercs_r.reset_RST(ARG_rst_in);
  INST_r_delay0_sckcs_r.reset_RST(ARG_rst_in);
  INST_r_delay0_cssck_r.reset_RST(ARG_rst_in);
  INST_r_csmode_r.reset_RST(ARG_rst_in);
  INST_r_csid_r.reset_RST(ARG_rst_in);
  INST_r_csdef_r.reset_RST(ARG_rst_in);
  INST_ph3.reset_RST(ARG_rst_in);
  INST_ph2.reset_RST(ARG_rst_in);
  INST_bad.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkSpiRegsTbLines4::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkSpiRegsTbLines4::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_bad.dump_state(indent + 2u);
  INST_ph2.dump_state(indent + 2u);
  INST_ph3.dump_state(indent + 2u);
  INST_r_csdef_r.dump_state(indent + 2u);
  INST_r_csid_r.dump_state(indent + 2u);
  INST_r_csmode_r.dump_state(indent + 2u);
  INST_r_delay0_cssck_r.dump_state(indent + 2u);
  INST_r_delay0_sckcs_r.dump_state(indent + 2u);
  INST_r_delay1_intercs_r.dump_state(indent + 2u);
  INST_r_delay1_interxfr_r.dump_state(indent + 2u);
  INST_r_fmt_dir_r.dump_state(indent + 2u);
  INST_r_fmt_endian_r.dump_state(indent + 2u);
  INST_r_fmt_len_r.dump_state(indent + 2u);
  INST_r_fmt_proto_r.dump_state(indent + 2u);
  INST_r_ie_rxwm_r.dump_state(indent + 2u);
  INST_r_ie_txwm_r.dump_state(indent + 2u);
  INST_r_ip_rxwm_r.dump_state(indent + 2u);
  INST_r_ip_txwm_r.dump_state(indent + 2u);
  INST_r_rxdata_data_acc.dump_state(indent + 2u);
  INST_r_rxdata_data_r.dump_state(indent + 2u);
  INST_r_rxdata_empty_r.dump_state(indent + 2u);
  INST_r_rxmark_r.dump_state(indent + 2u);
  INST_r_sckdiv_r.dump_state(indent + 2u);
  INST_r_sckmode_pha_r.dump_state(indent + 2u);
  INST_r_sckmode_pol_r.dump_state(indent + 2u);
  INST_r_txdata_data_mod.dump_state(indent + 2u);
  INST_r_txdata_data_r.dump_state(indent + 2u);
  INST_r_txdata_full_r.dump_state(indent + 2u);
  INST_r_txmark_r.dump_state(indent + 2u);
  INST_rstp.dump_state(indent + 2u);
  INST_step.dump_state(indent + 2u);
  INST_wstp.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkSpiRegsTbLines4::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 39u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_0_CONCAT_r_fmt_len_r_04___d105", 16u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h24709", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h24713", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h24718", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h24725", 4u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y_avValue_rdata__h24746", 32u);
  num = INST_bad.dump_VCD_defs(num);
  num = INST_ph2.dump_VCD_defs(num);
  num = INST_ph3.dump_VCD_defs(num);
  num = INST_r_csdef_r.dump_VCD_defs(num);
  num = INST_r_csid_r.dump_VCD_defs(num);
  num = INST_r_csmode_r.dump_VCD_defs(num);
  num = INST_r_delay0_cssck_r.dump_VCD_defs(num);
  num = INST_r_delay0_sckcs_r.dump_VCD_defs(num);
  num = INST_r_delay1_intercs_r.dump_VCD_defs(num);
  num = INST_r_delay1_interxfr_r.dump_VCD_defs(num);
  num = INST_r_fmt_dir_r.dump_VCD_defs(num);
  num = INST_r_fmt_endian_r.dump_VCD_defs(num);
  num = INST_r_fmt_len_r.dump_VCD_defs(num);
  num = INST_r_fmt_proto_r.dump_VCD_defs(num);
  num = INST_r_ie_rxwm_r.dump_VCD_defs(num);
  num = INST_r_ie_txwm_r.dump_VCD_defs(num);
  num = INST_r_ip_rxwm_r.dump_VCD_defs(num);
  num = INST_r_ip_txwm_r.dump_VCD_defs(num);
  num = INST_r_rxdata_data_acc.dump_VCD_defs(num);
  num = INST_r_rxdata_data_r.dump_VCD_defs(num);
  num = INST_r_rxdata_empty_r.dump_VCD_defs(num);
  num = INST_r_rxmark_r.dump_VCD_defs(num);
  num = INST_r_sckdiv_r.dump_VCD_defs(num);
  num = INST_r_sckmode_pha_r.dump_VCD_defs(num);
  num = INST_r_sckmode_pol_r.dump_VCD_defs(num);
  num = INST_r_txdata_data_mod.dump_VCD_defs(num);
  num = INST_r_txdata_data_r.dump_VCD_defs(num);
  num = INST_r_txdata_full_r.dump_VCD_defs(num);
  num = INST_r_txmark_r.dump_VCD_defs(num);
  num = INST_rstp.dump_VCD_defs(num);
  num = INST_step.dump_VCD_defs(num);
  num = INST_wstp.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkSpiRegsTbLines4::dump_VCD(tVCDDumpType dt,
				     unsigned int levels,
				     MOD_mkSpiRegsTbLines4 &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkSpiRegsTbLines4::vcd_defs(tVCDDumpType dt, MOD_mkSpiRegsTbLines4 &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 16u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 4u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF__0_CONCAT_r_fmt_len_r_04___d105) != DEF__0_CONCAT_r_fmt_len_r_04___d105)
      {
	vcd_write_val(sim_hdl, num, DEF__0_CONCAT_r_fmt_len_r_04___d105, 16u);
	backing.DEF__0_CONCAT_r_fmt_len_r_04___d105 = DEF__0_CONCAT_r_fmt_len_r_04___d105;
      }
      ++num;
      if ((backing.DEF_x__h24709) != DEF_x__h24709)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h24709, 2u);
	backing.DEF_x__h24709 = DEF_x__h24709;
      }
      ++num;
      if ((backing.DEF_x__h24713) != DEF_x__h24713)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h24713, 1u);
	backing.DEF_x__h24713 = DEF_x__h24713;
      }
      ++num;
      if ((backing.DEF_x__h24718) != DEF_x__h24718)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h24718, 1u);
	backing.DEF_x__h24718 = DEF_x__h24718;
      }
      ++num;
      if ((backing.DEF_x__h24725) != DEF_x__h24725)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h24725, 4u);
	backing.DEF_x__h24725 = DEF_x__h24725;
      }
      ++num;
      if ((backing.DEF_y_avValue_rdata__h24746) != DEF_y_avValue_rdata__h24746)
      {
	vcd_write_val(sim_hdl, num, DEF_y_avValue_rdata__h24746, 32u);
	backing.DEF_y_avValue_rdata__h24746 = DEF_y_avValue_rdata__h24746;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF__0_CONCAT_r_fmt_len_r_04___d105, 16u);
      backing.DEF__0_CONCAT_r_fmt_len_r_04___d105 = DEF__0_CONCAT_r_fmt_len_r_04___d105;
      vcd_write_val(sim_hdl, num++, DEF_x__h24709, 2u);
      backing.DEF_x__h24709 = DEF_x__h24709;
      vcd_write_val(sim_hdl, num++, DEF_x__h24713, 1u);
      backing.DEF_x__h24713 = DEF_x__h24713;
      vcd_write_val(sim_hdl, num++, DEF_x__h24718, 1u);
      backing.DEF_x__h24718 = DEF_x__h24718;
      vcd_write_val(sim_hdl, num++, DEF_x__h24725, 4u);
      backing.DEF_x__h24725 = DEF_x__h24725;
      vcd_write_val(sim_hdl, num++, DEF_y_avValue_rdata__h24746, 32u);
      backing.DEF_y_avValue_rdata__h24746 = DEF_y_avValue_rdata__h24746;
    }
}

void MOD_mkSpiRegsTbLines4::vcd_prims(tVCDDumpType dt, MOD_mkSpiRegsTbLines4 &backing)
{
  INST_bad.dump_VCD(dt, backing.INST_bad);
  INST_ph2.dump_VCD(dt, backing.INST_ph2);
  INST_ph3.dump_VCD(dt, backing.INST_ph3);
  INST_r_csdef_r.dump_VCD(dt, backing.INST_r_csdef_r);
  INST_r_csid_r.dump_VCD(dt, backing.INST_r_csid_r);
  INST_r_csmode_r.dump_VCD(dt, backing.INST_r_csmode_r);
  INST_r_delay0_cssck_r.dump_VCD(dt, backing.INST_r_delay0_cssck_r);
  INST_r_delay0_sckcs_r.dump_VCD(dt, backing.INST_r_delay0_sckcs_r);
  INST_r_delay1_intercs_r.dump_VCD(dt, backing.INST_r_delay1_intercs_r);
  INST_r_delay1_interxfr_r.dump_VCD(dt, backing.INST_r_delay1_interxfr_r);
  INST_r_fmt_dir_r.dump_VCD(dt, backing.INST_r_fmt_dir_r);
  INST_r_fmt_endian_r.dump_VCD(dt, backing.INST_r_fmt_endian_r);
  INST_r_fmt_len_r.dump_VCD(dt, backing.INST_r_fmt_len_r);
  INST_r_fmt_proto_r.dump_VCD(dt, backing.INST_r_fmt_proto_r);
  INST_r_ie_rxwm_r.dump_VCD(dt, backing.INST_r_ie_rxwm_r);
  INST_r_ie_txwm_r.dump_VCD(dt, backing.INST_r_ie_txwm_r);
  INST_r_ip_rxwm_r.dump_VCD(dt, backing.INST_r_ip_rxwm_r);
  INST_r_ip_txwm_r.dump_VCD(dt, backing.INST_r_ip_txwm_r);
  INST_r_rxdata_data_acc.dump_VCD(dt, backing.INST_r_rxdata_data_acc);
  INST_r_rxdata_data_r.dump_VCD(dt, backing.INST_r_rxdata_data_r);
  INST_r_rxdata_empty_r.dump_VCD(dt, backing.INST_r_rxdata_empty_r);
  INST_r_rxmark_r.dump_VCD(dt, backing.INST_r_rxmark_r);
  INST_r_sckdiv_r.dump_VCD(dt, backing.INST_r_sckdiv_r);
  INST_r_sckmode_pha_r.dump_VCD(dt, backing.INST_r_sckmode_pha_r);
  INST_r_sckmode_pol_r.dump_VCD(dt, backing.INST_r_sckmode_pol_r);
  INST_r_txdata_data_mod.dump_VCD(dt, backing.INST_r_txdata_data_mod);
  INST_r_txdata_data_r.dump_VCD(dt, backing.INST_r_txdata_data_r);
  INST_r_txdata_full_r.dump_VCD(dt, backing.INST_r_txdata_full_r);
  INST_r_txmark_r.dump_VCD(dt, backing.INST_r_txmark_r);
  INST_rstp.dump_VCD(dt, backing.INST_rstp);
  INST_step.dump_VCD(dt, backing.INST_step);
  INST_wstp.dump_VCD(dt, backing.INST_wstp);
}
