/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Tue Sep 22 00:42:19 JST 2026
 * 
 */

/* Generation options: */
#ifndef __mkSpiLines4Tb_h__
#define __mkSpiLines4Tb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkSpiLines4Tb module */
class MOD_mkSpiLines4Tb : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_bad;
  MOD_CReg<tUInt8> INST_csHi;
  MOD_Reg<tUInt8> INST_csNow;
  MOD_Reg<tUInt8> INST_csPins;
  MOD_CReg<tUInt8> INST_csSaw;
  MOD_ConfigReg<tUInt32> INST_cyc;
  MOD_Reg<tUInt8> INST_got;
  MOD_Reg<tUInt8> INST_leadPend;
  MOD_Reg<tUInt32> INST_mGap;
  MOD_Reg<tUInt32> INST_mInact;
  MOD_Reg<tUInt32> INST_mLead;
  MOD_Reg<tUInt32> INST_mPerF;
  MOD_Reg<tUInt32> INST_mTail;
  MOD_Reg<tUInt32> INST_nEdgeF;
  MOD_Reg<tUInt32> INST_nOn;
  MOD_Reg<tUInt32> INST_onMark;
  MOD_Reg<tUInt8> INST_onWas;
  MOD_Reg<tUInt8> INST_ovfN;
  MOD_Reg<tUInt8> INST_ph;
  MOD_Reg<tUInt32> INST_s;
  MOD_Reg<tUInt8> INST_sawCs;
  MOD_Reg<tUInt8> INST_sckWas;
  MOD_Reg<tUInt8> INST_sent;
  MOD_Reg<tUInt8> INST_sp_bitn;
  MOD_ConfigReg<tUInt8> INST_sp_csAct;
  MOD_CReg<tUInt8> INST_sp_csDrop;
  MOD_ConfigReg<tUInt8> INST_sp_csOn;
  MOD_Reg<tUInt8> INST_sp_defWas;
  MOD_Reg<tUInt32> INST_sp_div;
  MOD_Reg<tUInt8> INST_sp_dly;
  MOD_Reg<tUInt8> INST_sp_half;
  MOD_Reg<tUInt8> INST_sp_idWas;
  MOD_Wire<tUInt8> INST_sp_ioIn;
  MOD_Reg<tUInt8> INST_sp_modeWas;
  MOD_Reg<tUInt8> INST_sp_r_csdef_r;
  MOD_Reg<tUInt8> INST_sp_r_csid_r;
  MOD_Reg<tUInt8> INST_sp_r_csmode_r;
  MOD_Reg<tUInt8> INST_sp_r_delay0_cssck_r;
  MOD_Reg<tUInt8> INST_sp_r_delay0_sckcs_r;
  MOD_Reg<tUInt8> INST_sp_r_delay1_intercs_r;
  MOD_Reg<tUInt8> INST_sp_r_delay1_interxfr_r;
  MOD_Reg<tUInt8> INST_sp_r_fmt_dir_r;
  MOD_Reg<tUInt8> INST_sp_r_fmt_endian_r;
  MOD_Reg<tUInt8> INST_sp_r_fmt_len_r;
  MOD_Reg<tUInt8> INST_sp_r_fmt_proto_r;
  MOD_Reg<tUInt8> INST_sp_r_ie_rxwm_r;
  MOD_Reg<tUInt8> INST_sp_r_ie_txwm_r;
  MOD_Wire<tUInt8> INST_sp_r_ip_rxwm_r;
  MOD_Wire<tUInt8> INST_sp_r_ip_txwm_r;
  MOD_Wire<tUInt8> INST_sp_r_rxdata_data_acc;
  MOD_Wire<tUInt8> INST_sp_r_rxdata_data_r;
  MOD_Wire<tUInt8> INST_sp_r_rxdata_empty_r;
  MOD_Reg<tUInt8> INST_sp_r_rxmark_r;
  MOD_Reg<tUInt32> INST_sp_r_sckdiv_r;
  MOD_Reg<tUInt8> INST_sp_r_sckmode_pha_r;
  MOD_Reg<tUInt8> INST_sp_r_sckmode_pol_r;
  MOD_Wire<tUInt8> INST_sp_r_txdata_data_mod;
  MOD_Reg<tUInt8> INST_sp_r_txdata_data_r;
  MOD_Wire<tUInt8> INST_sp_r_txdata_full_r;
  MOD_Reg<tUInt8> INST_sp_r_txmark_r;
  MOD_Reg<tUInt8> INST_sp_rxIn;
  MOD_Reg<tUInt8> INST_sp_rxOut;
  MOD_Fifo<tUInt8> INST_sp_rxq;
  MOD_Reg<tUInt8> INST_sp_shRx;
  MOD_Reg<tUInt8> INST_sp_shTx;
  MOD_ConfigReg<tUInt8> INST_sp_st;
  MOD_Reg<tUInt8> INST_sp_txIn;
  MOD_Reg<tUInt8> INST_sp_txOut;
  MOD_Reg<tUInt8> INST_sp_txPend;
  MOD_Fifo<tUInt8> INST_sp_txq;
  MOD_Reg<tUInt32> INST_tEdge;
  MOD_Reg<tUInt32> INST_tOff;
  MOD_Reg<tUInt32> INST_tOn;
  MOD_Reg<tUInt32> INST_vautoA;
  MOD_Reg<tUInt32> INST_vautoB;
  MOD_Reg<tUInt32> INST_vgapA;
  MOD_Reg<tUInt32> INST_vgapB;
  MOD_Reg<tUInt32> INST_vinactA;
  MOD_Reg<tUInt32> INST_vinactC;
  MOD_Reg<tUInt32> INST_vleadA;
  MOD_Reg<tUInt32> INST_vleadB;
  MOD_Reg<tUInt32> INST_vleadC;
  MOD_Reg<tUInt32> INST_vtailA;
  MOD_Reg<tUInt32> INST_vtailB;
  MOD_Reg<tUInt32> INST_vtailC;
 
 /* Constructor */
 public:
  MOD_mkSpiLines4Tb(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_sp_st_read__5_EQ_3___d77;
  tUInt8 DEF_sp_txq_i_notEmpty____d35;
  tUInt8 DEF_x__h3222;
  tUInt8 DEF_x__h9474;
  tUInt8 DEF_ph__h6611;
  tUInt8 DEF_sp_st_read____d25;
  tUInt8 DEF_sp_rxq_i_notEmpty____d122;
  tUInt8 DEF_sp_txq_i_notFull____d3;
  tUInt8 DEF_sp_st_read__5_EQ_4___d55;
 
 /* Local definitions */
 private:
  tUInt8 DEF_sp_r_rxdata_empty_r_wget____d218;
  tUInt8 DEF_sp_r_rxdata_empty_r_whas____d216;
  tUInt8 DEF_x__h9703;
  tUInt8 DEF_NOT_sp_r_rxdata_empty_r_whas__16_17_OR_NOT_sp__ETC___d220;
  tUInt8 DEF_sp_r_rxdata_empty_r_whas__16_AND_sp_r_rxdata_e_ETC___d247;
  tUInt32 DEF_x__h72319;
  tUInt8 DEF_phase__h3915;
  tUInt8 DEF_sp_csOn_read____d23;
  tUInt8 DEF_x__h2524;
  tUInt8 DEF_NOT_s_91_EQ_0_92_94_AND_NOT_s_91_EQ_1_93_95___d196;
  tUInt32 DEF_x__h73658;
  tUInt8 DEF_s_91_ULT_2___d197;
  tUInt32 DEF_x__h73811;
  tUInt32 DEF_x__h71671;
  tUInt32 DEF_x__h61518;
  tUInt32 DEF_x__h56355;
  tUInt32 DEF_x__h49108;
  tUInt32 DEF_x__h6583;
  tUInt32 DEF_x__h73677;
  tUInt32 DEF_x__h3449;
  tUInt32 DEF_x__h3451;
  tUInt8 DEF_x__h3913;
  tUInt8 DEF_x__h3662;
  tUInt8 DEF_x__h2934;
  tUInt8 DEF_x__h2289;
  tUInt8 DEF__read__h1616;
  tUInt8 DEF_x_wget__h737;
  tUInt8 DEF_x__h2609;
  tUInt8 DEF_sp_r_ip_rxwm_r_whas____d256;
  tUInt8 DEF_x_wget__h1086;
  tUInt8 DEF_sp_r_fmt_endian_r__h3562;
  tUInt8 DEF_x__h26990;
  tUInt8 DEF_sp_r_csid_r__h2739;
  tUInt8 DEF_csPins__h34120;
  tUInt32 DEF_IF_s_91_PLUS_1_98_ULT_2_56_THEN_s_91_PLUS_1_98_ETC___d357;
  tUInt8 DEF_s_91_PLUS_1_98_ULT_2___d356;
  tUInt32 DEF_IF_s_91_EQ_65535_26_THEN_s_91_PLUS_1_98_ELSE_0___d327;
  tUInt8 DEF_s_91_EQ_65535___d326;
  tUInt8 DEF_s_91_ULT_64___d286;
  tUInt32 DEF_IF_s_91_ULT_2_97_THEN_s_91_PLUS_1_98_ELSE_0___d199;
  tUInt32 DEF_IF_s_91_ULE_600_40_THEN_s_91_PLUS_1_98_ELSE_0___d241;
  tUInt8 DEF_s_91_ULE_600___d240;
  tUInt32 DEF_IF_s_91_EQ_0_92_THEN_s_91_PLUS_1_98_ELSE_0___d333;
  tUInt8 DEF_s_91_EQ_0___d192;
  tUInt32 DEF_IF_sp_div_5_EQ_0_6_THEN_sp_r_sckdiv_r_7_ELSE_s_ETC___d68;
  tUInt8 DEF_sp_div_5_EQ_0___d66;
  tUInt32 DEF_x__h3430;
  tUInt8 DEF__0_CONCAT_sp_shTx_9_BITS_7_TO_4_0___d91;
  tUInt8 DEF_NOT_sp_r_csdef_r_0___d142;
  tUInt8 DEF_s_91_EQ_1___d193;
  tUInt8 DEF_sp_r_csmode_r_EQ_3___d30;
  tUInt8 DEF_sp_r_rxdata_empty_r_whas__16_AND_sp_r_rxdata_e_ETC___d250;
  tUInt8 DEF_NOT_IF_sp_r_rxdata_data_r_whas__21_THEN_sp_r_r_ETC___d249;
  tUInt8 DEF_NOT_s_91_ULT_64_86_87_AND_csPins_88___d289;
  tUInt8 DEF_NOT_s_91_ULT_64_86___d287;
  tUInt8 DEF_NOT_s_91_ULE_600_40_42_AND_NOT_csHi_port1__rea_ETC___d294;
  tUInt8 DEF_NOT_s_91_ULE_600_40___d242;
  tUInt8 DEF_NOT_s_91_EQ_1_93___d195;
  tUInt8 DEF_NOT_sp_r_rxdata_empty_r_whas__16_17_OR_NOT_sp__ETC___d251;
  tUInt8 DEF_NOT_s_91_EQ_0_92___d194;
  tUInt8 DEF_NOT_sp_half_9___d70;
  tUInt8 DEF_NOT_sp_r_csmode_r_EQ_3_0___d31;
  tUInt8 DEF_NOT_s_91_PLUS_1_98_ULT_2_56___d358;
  tUInt8 DEF_NOT_s_91_EQ_65535_26___d328;
  tUInt8 DEF_y__h2715;
 
 /* Rules */
 public:
  void RL_sp_mark();
  void RL_sp_push();
  void RL_sp_csTrack();
  void RL_sp_idle();
  void RL_sp_load();
  void RL_sp_tick();
  void RL_sp_waited();
  void RL_sp_step();
  void RL_sp_status();
  void RL_sp_pop();
  void RL_loop();
  void RL_timeout();
  void RL_setup();
  void RL_send();
  void RL_sendDone();
  void RL_recv();
  void RL_dirSet();
  void RL_dirWait();
  void RL_dirCheck();
  void RL_lsbSet();
  void RL_lsbWait();
  void RL_lsbCheck();
  void RL_wmA();
  void RL_wmB();
  void RL_wmC();
  void RL_wmD();
  void RL_wmE();
  void RL_csOffA();
  void RL_csOffB();
  void RL_csOffC();
  void RL_csHoldA();
  void RL_csHoldB();
  void RL_csHoldC();
  void RL_csHoldD();
  void RL_flush();
  void RL_phaA();
  void RL_phaB();
  void RL_phaC();
  void RL_phaD();
  void RL_csdA();
  void RL_csdB();
  void RL_csdC();
  void RL_csdD();
  void RL_csdE();
  void RL_csdF();
  void RL_holdA();
  void RL_holdB();
  void RL_holdC();
  void RL_holdD();
  void RL_holdE();
  void RL_holdF();
  void RL_holdG();
  void RL_holdJ();
  void RL_holdJ2();
  void RL_holdJ3();
  void RL_holdK();
  void RL_holdL();
  void RL_holdM();
  void RL_flush2();
  void RL_r0w();
  void RL_r0s();
  void RL_r0q();
  void RL_r0m();
  void RL_r1w();
  void RL_r1s();
  void RL_r1q();
  void RL_r1m();
  void RL_r2w();
  void RL_r2s();
  void RL_r2q();
  void RL_r2m();
  void RL_r3w();
  void RL_r3s();
  void RL_r3q();
  void RL_r3m();
  void RL_r4w();
  void RL_r4s();
  void RL_r4q();
  void RL_r4m();
  void RL_r5w();
  void RL_r5s();
  void RL_r5q();
  void RL_r5m();
  void RL_r6w();
  void RL_r6s();
  void RL_r6q();
  void RL_r6m();
  void RL_r7w();
  void RL_r7s();
  void RL_r7q();
  void RL_r7m();
  void RL_r8w();
  void RL_r8s();
  void RL_r8q();
  void RL_r8m();
  void RL_r9w();
  void RL_r9s();
  void RL_r9q();
  void RL_r9m();
  void RL_r10w();
  void RL_r10s();
  void RL_r10q();
  void RL_r10m();
  void RL_r11w();
  void RL_r11s();
  void RL_r11q();
  void RL_r11m();
  void RL_tmChk();
  void RL_flush3();
  void RL_ovfM();
  void RL_ovfA();
  void RL_ovfB();
  void RL_ovfC();
  void RL_flush4();
  void RL_fin();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkSpiLines4Tb &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkSpiLines4Tb &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkSpiLines4Tb &backing);
};

#endif /* ifndef __mkSpiLines4Tb_h__ */
