/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Tue Sep 22 00:42:19 JST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkSpiLines4Tb.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkSpiLines4Tb::MODEL_mkSpiLines4Tb()
{
  mkSpiLines4Tb_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkSpiLines4Tb()
{
  MODEL_mkSpiLines4Tb *model = new MODEL_mkSpiLines4Tb();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkSpiLines4Tb &INST_top = *((MOD_mkSpiLines4Tb *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_sp_st_read__5_EQ_1_4_OR_sp_st_read__5_EQ_4_5_6_ETC___d60;
	 tUInt8 DEF_INST_top_DEF_ph_89_EQ_1___d200;
	 tUInt8 DEF_INST_top_DEF_sp_dly_1_EQ_0___d62;
	 tUInt8 DEF_INST_top_DEF_sp_txPend__h2240;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_sp_mark;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_sp_mark;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_sp_push;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_sp_push;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_sp_csTrack;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_sp_csTrack;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_sp_idle;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_sp_idle;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_sp_load;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_sp_load;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_sp_tick;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_sp_tick;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_sp_waited;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_sp_waited;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_sp_step;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_sp_step;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_sp_status;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_sp_status;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_sp_pop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_sp_pop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_loop;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_loop;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_timeout;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_timeout;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_setup;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_setup;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_send;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_send;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_sendDone;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_sendDone;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_recv;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_recv;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dirSet;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dirSet;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dirWait;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dirWait;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_dirCheck;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_dirCheck;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_lsbSet;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_lsbSet;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_lsbWait;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_lsbWait;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_lsbCheck;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_lsbCheck;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_wmA;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_wmA;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_wmB;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_wmB;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_wmC;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_wmC;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_wmD;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_wmD;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_wmE;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_wmE;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csOffA;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csOffA;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csOffB;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csOffB;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csOffC;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csOffC;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csHoldA;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csHoldA;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csHoldB;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csHoldB;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csHoldC;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csHoldC;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csHoldD;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csHoldD;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_flush;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_flush;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_phaA;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_phaA;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_phaB;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_phaB;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_phaC;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_phaC;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_phaD;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_phaD;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csdA;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csdA;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csdB;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csdB;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csdC;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csdC;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csdD;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csdD;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csdE;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csdE;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_csdF;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_csdF;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdA;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdA;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdB;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdB;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdC;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdC;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdD;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdD;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdE;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdE;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdF;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdF;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdG;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdG;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdJ;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdJ;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdJ2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdJ2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdJ3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdJ3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdK;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdK;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdL;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdL;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_holdM;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_holdM;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_flush2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_flush2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r0w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r0w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r0s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r0s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r0q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r0q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r0m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r0m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r1w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r1w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r1s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r1s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r1q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r1q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r1m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r1m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r2w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r2w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r2s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r2s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r2q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r2q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r2m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r2m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r3w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r3w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r3s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r3s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r3q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r3q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r3m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r3m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r4w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r4w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r4s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r4s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r4q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r4q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r4m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r4m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r5w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r5w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r5s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r5s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r5q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r5q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r5m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r5m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r6w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r6w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r6s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r6s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r6q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r6q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r6m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r6m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r7w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r7w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r7s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r7s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r7q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r7q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r7m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r7m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r8w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r8w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r8s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r8s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r8q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r8q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r8m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r8m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r9w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r9w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r9s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r9s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r9q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r9q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r9m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r9m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r10w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r10w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r10s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r10s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r10q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r10q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r10m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r10m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r11w;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r11w;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r11s;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r11s;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r11q;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r11q;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_r11m;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_r11m;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_tmChk;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_tmChk;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_flush3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_flush3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ovfM;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ovfM;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ovfA;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ovfA;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ovfB;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ovfB;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_ovfC;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_ovfC;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_flush4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_flush4;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fin;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fin;
	 INST_top.DEF_ph__h6611 = INST_top.INST_ph.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_csHoldA = (INST_top.DEF_ph__h6611) == (tUInt8)11u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csHoldA = DEF_INST_top_DEF_CAN_FIRE_RL_csHoldA;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csHoldB = (INST_top.DEF_ph__h6611) == (tUInt8)12u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csHoldB = DEF_INST_top_DEF_CAN_FIRE_RL_csHoldB;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csHoldC = (INST_top.DEF_ph__h6611) == (tUInt8)13u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csHoldC = DEF_INST_top_DEF_CAN_FIRE_RL_csHoldC;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csHoldD = (INST_top.DEF_ph__h6611) == (tUInt8)14u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csHoldD = DEF_INST_top_DEF_CAN_FIRE_RL_csHoldD;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csOffA = (INST_top.DEF_ph__h6611) == (tUInt8)8u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csOffA = DEF_INST_top_DEF_CAN_FIRE_RL_csOffA;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csOffB = (INST_top.DEF_ph__h6611) == (tUInt8)9u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csOffB = DEF_INST_top_DEF_CAN_FIRE_RL_csOffB;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csOffC = (INST_top.DEF_ph__h6611) == (tUInt8)10u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csOffC = DEF_INST_top_DEF_CAN_FIRE_RL_csOffC;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csdA = (INST_top.DEF_ph__h6611) == (tUInt8)20u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csdA = DEF_INST_top_DEF_CAN_FIRE_RL_csdA;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csdB = (INST_top.DEF_ph__h6611) == (tUInt8)21u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csdB = DEF_INST_top_DEF_CAN_FIRE_RL_csdB;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csdC = (INST_top.DEF_ph__h6611) == (tUInt8)22u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csdC = DEF_INST_top_DEF_CAN_FIRE_RL_csdC;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csdD = (INST_top.DEF_ph__h6611) == (tUInt8)23u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csdD = DEF_INST_top_DEF_CAN_FIRE_RL_csdD;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csdE = (INST_top.DEF_ph__h6611) == (tUInt8)24u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csdE = DEF_INST_top_DEF_CAN_FIRE_RL_csdE;
	 DEF_INST_top_DEF_CAN_FIRE_RL_csdF = (INST_top.DEF_ph__h6611) == (tUInt8)25u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_csdF = DEF_INST_top_DEF_CAN_FIRE_RL_csdF;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dirSet = (INST_top.DEF_ph__h6611) == (tUInt8)97u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_dirSet = DEF_INST_top_DEF_CAN_FIRE_RL_dirSet;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dirCheck = (INST_top.DEF_ph__h6611) == (tUInt8)99u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_dirCheck = DEF_INST_top_DEF_CAN_FIRE_RL_dirCheck;
	 DEF_INST_top_DEF_CAN_FIRE_RL_dirWait = (INST_top.DEF_ph__h6611) == (tUInt8)98u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_dirWait = DEF_INST_top_DEF_CAN_FIRE_RL_dirWait;
	 DEF_INST_top_DEF_CAN_FIRE_RL_fin = (INST_top.DEF_ph__h6611) == (tUInt8)103u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_fin = DEF_INST_top_DEF_CAN_FIRE_RL_fin;
	 DEF_INST_top_DEF_CAN_FIRE_RL_flush = (INST_top.DEF_ph__h6611) == (tUInt8)15u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_flush = DEF_INST_top_DEF_CAN_FIRE_RL_flush;
	 DEF_INST_top_DEF_CAN_FIRE_RL_flush2 = (INST_top.DEF_ph__h6611) == (tUInt8)41u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_flush2 = DEF_INST_top_DEF_CAN_FIRE_RL_flush2;
	 DEF_INST_top_DEF_CAN_FIRE_RL_flush3 = (INST_top.DEF_ph__h6611) == (tUInt8)91u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_flush3 = DEF_INST_top_DEF_CAN_FIRE_RL_flush3;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdA = (INST_top.DEF_ph__h6611) == (tUInt8)26u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdA = DEF_INST_top_DEF_CAN_FIRE_RL_holdA;
	 DEF_INST_top_DEF_CAN_FIRE_RL_flush4 = (INST_top.DEF_ph__h6611) == (tUInt8)96u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_flush4 = DEF_INST_top_DEF_CAN_FIRE_RL_flush4;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdB = (INST_top.DEF_ph__h6611) == (tUInt8)27u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdB = DEF_INST_top_DEF_CAN_FIRE_RL_holdB;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdC = (INST_top.DEF_ph__h6611) == (tUInt8)28u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdC = DEF_INST_top_DEF_CAN_FIRE_RL_holdC;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdD = (INST_top.DEF_ph__h6611) == (tUInt8)29u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdD = DEF_INST_top_DEF_CAN_FIRE_RL_holdD;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdE = (INST_top.DEF_ph__h6611) == (tUInt8)30u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdE = DEF_INST_top_DEF_CAN_FIRE_RL_holdE;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdF = (INST_top.DEF_ph__h6611) == (tUInt8)31u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdF = DEF_INST_top_DEF_CAN_FIRE_RL_holdF;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdJ = (INST_top.DEF_ph__h6611) == (tUInt8)35u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdJ = DEF_INST_top_DEF_CAN_FIRE_RL_holdJ;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdG = (INST_top.DEF_ph__h6611) == (tUInt8)32u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdG = DEF_INST_top_DEF_CAN_FIRE_RL_holdG;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdJ2 = (INST_top.DEF_ph__h6611) == (tUInt8)36u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdJ2 = DEF_INST_top_DEF_CAN_FIRE_RL_holdJ2;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdJ3 = (INST_top.DEF_ph__h6611) == (tUInt8)37u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdJ3 = DEF_INST_top_DEF_CAN_FIRE_RL_holdJ3;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdK = (INST_top.DEF_ph__h6611) == (tUInt8)38u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdK = DEF_INST_top_DEF_CAN_FIRE_RL_holdK;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdL = (INST_top.DEF_ph__h6611) == (tUInt8)39u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdL = DEF_INST_top_DEF_CAN_FIRE_RL_holdL;
	 DEF_INST_top_DEF_CAN_FIRE_RL_holdM = (INST_top.DEF_ph__h6611) == (tUInt8)40u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_holdM = DEF_INST_top_DEF_CAN_FIRE_RL_holdM;
	 DEF_INST_top_DEF_CAN_FIRE_RL_loop = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_loop = DEF_INST_top_DEF_CAN_FIRE_RL_loop;
	 DEF_INST_top_DEF_CAN_FIRE_RL_lsbCheck = (INST_top.DEF_ph__h6611) == (tUInt8)102u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_lsbCheck = DEF_INST_top_DEF_CAN_FIRE_RL_lsbCheck;
	 DEF_INST_top_DEF_CAN_FIRE_RL_lsbSet = (INST_top.DEF_ph__h6611) == (tUInt8)100u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_lsbSet = DEF_INST_top_DEF_CAN_FIRE_RL_lsbSet;
	 DEF_INST_top_DEF_CAN_FIRE_RL_lsbWait = (INST_top.DEF_ph__h6611) == (tUInt8)101u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_lsbWait = DEF_INST_top_DEF_CAN_FIRE_RL_lsbWait;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ovfA = (INST_top.DEF_ph__h6611) == (tUInt8)93u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ovfA = DEF_INST_top_DEF_CAN_FIRE_RL_ovfA;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ovfB = (INST_top.DEF_ph__h6611) == (tUInt8)94u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ovfB = DEF_INST_top_DEF_CAN_FIRE_RL_ovfB;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ovfC = (INST_top.DEF_ph__h6611) == (tUInt8)95u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ovfC = DEF_INST_top_DEF_CAN_FIRE_RL_ovfC;
	 DEF_INST_top_DEF_CAN_FIRE_RL_ovfM = (INST_top.DEF_ph__h6611) == (tUInt8)92u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_ovfM = DEF_INST_top_DEF_CAN_FIRE_RL_ovfM;
	 DEF_INST_top_DEF_CAN_FIRE_RL_phaB = (INST_top.DEF_ph__h6611) == (tUInt8)17u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_phaB = DEF_INST_top_DEF_CAN_FIRE_RL_phaB;
	 DEF_INST_top_DEF_CAN_FIRE_RL_phaA = (INST_top.DEF_ph__h6611) == (tUInt8)16u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_phaA = DEF_INST_top_DEF_CAN_FIRE_RL_phaA;
	 DEF_INST_top_DEF_CAN_FIRE_RL_phaC = (INST_top.DEF_ph__h6611) == (tUInt8)18u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_phaC = DEF_INST_top_DEF_CAN_FIRE_RL_phaC;
	 DEF_INST_top_DEF_CAN_FIRE_RL_phaD = (INST_top.DEF_ph__h6611) == (tUInt8)19u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_phaD = DEF_INST_top_DEF_CAN_FIRE_RL_phaD;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r0m = (INST_top.DEF_ph__h6611) == (tUInt8)45u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r0m = DEF_INST_top_DEF_CAN_FIRE_RL_r0m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r0q = (INST_top.DEF_ph__h6611) == (tUInt8)44u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r0q = DEF_INST_top_DEF_CAN_FIRE_RL_r0q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r0s = (INST_top.DEF_ph__h6611) == (tUInt8)43u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r0s = DEF_INST_top_DEF_CAN_FIRE_RL_r0s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r10m = (INST_top.DEF_ph__h6611) == (tUInt8)85u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r10m = DEF_INST_top_DEF_CAN_FIRE_RL_r10m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r0w = (INST_top.DEF_ph__h6611) == (tUInt8)42u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r0w = DEF_INST_top_DEF_CAN_FIRE_RL_r0w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r10q = (INST_top.DEF_ph__h6611) == (tUInt8)84u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r10q = DEF_INST_top_DEF_CAN_FIRE_RL_r10q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r10s = (INST_top.DEF_ph__h6611) == (tUInt8)83u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r10s = DEF_INST_top_DEF_CAN_FIRE_RL_r10s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r10w = (INST_top.DEF_ph__h6611) == (tUInt8)82u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r10w = DEF_INST_top_DEF_CAN_FIRE_RL_r10w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r11m = (INST_top.DEF_ph__h6611) == (tUInt8)89u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r11m = DEF_INST_top_DEF_CAN_FIRE_RL_r11m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r11q = (INST_top.DEF_ph__h6611) == (tUInt8)88u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r11q = DEF_INST_top_DEF_CAN_FIRE_RL_r11q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r11w = (INST_top.DEF_ph__h6611) == (tUInt8)86u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r11w = DEF_INST_top_DEF_CAN_FIRE_RL_r11w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r11s = (INST_top.DEF_ph__h6611) == (tUInt8)87u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r11s = DEF_INST_top_DEF_CAN_FIRE_RL_r11s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r1m = (INST_top.DEF_ph__h6611) == (tUInt8)49u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r1m = DEF_INST_top_DEF_CAN_FIRE_RL_r1m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r1q = (INST_top.DEF_ph__h6611) == (tUInt8)48u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r1q = DEF_INST_top_DEF_CAN_FIRE_RL_r1q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r1s = (INST_top.DEF_ph__h6611) == (tUInt8)47u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r1s = DEF_INST_top_DEF_CAN_FIRE_RL_r1s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r1w = (INST_top.DEF_ph__h6611) == (tUInt8)46u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r1w = DEF_INST_top_DEF_CAN_FIRE_RL_r1w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r2m = (INST_top.DEF_ph__h6611) == (tUInt8)53u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r2m = DEF_INST_top_DEF_CAN_FIRE_RL_r2m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r2q = (INST_top.DEF_ph__h6611) == (tUInt8)52u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r2q = DEF_INST_top_DEF_CAN_FIRE_RL_r2q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r2s = (INST_top.DEF_ph__h6611) == (tUInt8)51u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r2s = DEF_INST_top_DEF_CAN_FIRE_RL_r2s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r2w = (INST_top.DEF_ph__h6611) == (tUInt8)50u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r2w = DEF_INST_top_DEF_CAN_FIRE_RL_r2w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r3m = (INST_top.DEF_ph__h6611) == (tUInt8)57u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r3m = DEF_INST_top_DEF_CAN_FIRE_RL_r3m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r3q = (INST_top.DEF_ph__h6611) == (tUInt8)56u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r3q = DEF_INST_top_DEF_CAN_FIRE_RL_r3q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r3s = (INST_top.DEF_ph__h6611) == (tUInt8)55u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r3s = DEF_INST_top_DEF_CAN_FIRE_RL_r3s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r3w = (INST_top.DEF_ph__h6611) == (tUInt8)54u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r3w = DEF_INST_top_DEF_CAN_FIRE_RL_r3w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r4m = (INST_top.DEF_ph__h6611) == (tUInt8)61u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r4m = DEF_INST_top_DEF_CAN_FIRE_RL_r4m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r4s = (INST_top.DEF_ph__h6611) == (tUInt8)59u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r4s = DEF_INST_top_DEF_CAN_FIRE_RL_r4s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r4q = (INST_top.DEF_ph__h6611) == (tUInt8)60u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r4q = DEF_INST_top_DEF_CAN_FIRE_RL_r4q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r4w = (INST_top.DEF_ph__h6611) == (tUInt8)58u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r4w = DEF_INST_top_DEF_CAN_FIRE_RL_r4w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r5m = (INST_top.DEF_ph__h6611) == (tUInt8)65u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r5m = DEF_INST_top_DEF_CAN_FIRE_RL_r5m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r5q = (INST_top.DEF_ph__h6611) == (tUInt8)64u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r5q = DEF_INST_top_DEF_CAN_FIRE_RL_r5q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r5s = (INST_top.DEF_ph__h6611) == (tUInt8)63u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r5s = DEF_INST_top_DEF_CAN_FIRE_RL_r5s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r5w = (INST_top.DEF_ph__h6611) == (tUInt8)62u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r5w = DEF_INST_top_DEF_CAN_FIRE_RL_r5w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r6q = (INST_top.DEF_ph__h6611) == (tUInt8)68u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r6q = DEF_INST_top_DEF_CAN_FIRE_RL_r6q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r6m = (INST_top.DEF_ph__h6611) == (tUInt8)69u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r6m = DEF_INST_top_DEF_CAN_FIRE_RL_r6m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r6s = (INST_top.DEF_ph__h6611) == (tUInt8)67u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r6s = DEF_INST_top_DEF_CAN_FIRE_RL_r6s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r6w = (INST_top.DEF_ph__h6611) == (tUInt8)66u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r6w = DEF_INST_top_DEF_CAN_FIRE_RL_r6w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r7m = (INST_top.DEF_ph__h6611) == (tUInt8)73u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r7m = DEF_INST_top_DEF_CAN_FIRE_RL_r7m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r7q = (INST_top.DEF_ph__h6611) == (tUInt8)72u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r7q = DEF_INST_top_DEF_CAN_FIRE_RL_r7q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r7s = (INST_top.DEF_ph__h6611) == (tUInt8)71u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r7s = DEF_INST_top_DEF_CAN_FIRE_RL_r7s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r8m = (INST_top.DEF_ph__h6611) == (tUInt8)77u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r8m = DEF_INST_top_DEF_CAN_FIRE_RL_r8m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r7w = (INST_top.DEF_ph__h6611) == (tUInt8)70u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r7w = DEF_INST_top_DEF_CAN_FIRE_RL_r7w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r8q = (INST_top.DEF_ph__h6611) == (tUInt8)76u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r8q = DEF_INST_top_DEF_CAN_FIRE_RL_r8q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r8s = (INST_top.DEF_ph__h6611) == (tUInt8)75u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r8s = DEF_INST_top_DEF_CAN_FIRE_RL_r8s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r8w = (INST_top.DEF_ph__h6611) == (tUInt8)74u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r8w = DEF_INST_top_DEF_CAN_FIRE_RL_r8w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r9m = (INST_top.DEF_ph__h6611) == (tUInt8)81u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r9m = DEF_INST_top_DEF_CAN_FIRE_RL_r9m;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r9q = (INST_top.DEF_ph__h6611) == (tUInt8)80u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r9q = DEF_INST_top_DEF_CAN_FIRE_RL_r9q;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r9w = (INST_top.DEF_ph__h6611) == (tUInt8)78u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r9w = DEF_INST_top_DEF_CAN_FIRE_RL_r9w;
	 DEF_INST_top_DEF_CAN_FIRE_RL_r9s = (INST_top.DEF_ph__h6611) == (tUInt8)79u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_r9s = DEF_INST_top_DEF_CAN_FIRE_RL_r9s;
	 DEF_INST_top_DEF_CAN_FIRE_RL_recv = (INST_top.DEF_ph__h6611) == (tUInt8)2u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_recv = DEF_INST_top_DEF_CAN_FIRE_RL_recv;
	 INST_top.DEF_x__h9474 = INST_top.INST_sent.METH_read();
	 DEF_INST_top_DEF_ph_89_EQ_1___d200 = (INST_top.DEF_ph__h6611) == (tUInt8)1u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_send = DEF_INST_top_DEF_ph_89_EQ_1___d200 && (INST_top.DEF_x__h9474) < (tUInt8)4u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_send = DEF_INST_top_DEF_CAN_FIRE_RL_send;
	 DEF_INST_top_DEF_CAN_FIRE_RL_sendDone = DEF_INST_top_DEF_ph_89_EQ_1___d200 && (INST_top.DEF_x__h9474) == (tUInt8)4u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_sendDone = DEF_INST_top_DEF_CAN_FIRE_RL_sendDone;
	 DEF_INST_top_DEF_CAN_FIRE_RL_setup = (INST_top.DEF_ph__h6611) == (tUInt8)0u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_setup = DEF_INST_top_DEF_CAN_FIRE_RL_setup;
	 DEF_INST_top_DEF_CAN_FIRE_RL_sp_csTrack = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_sp_csTrack = DEF_INST_top_DEF_CAN_FIRE_RL_sp_csTrack;
	 INST_top.DEF_sp_txq_i_notEmpty____d35 = INST_top.INST_sp_txq.METH_i_notEmpty();
	 INST_top.DEF_sp_st_read____d25 = INST_top.INST_sp_st.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_sp_load = INST_top.DEF_sp_txq_i_notEmpty____d35 && (INST_top.DEF_sp_st_read____d25) == (tUInt8)2u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_sp_load = DEF_INST_top_DEF_CAN_FIRE_RL_sp_load;
	 DEF_INST_top_DEF_CAN_FIRE_RL_sp_idle = (INST_top.DEF_sp_st_read____d25) == (tUInt8)0u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_sp_idle = DEF_INST_top_DEF_CAN_FIRE_RL_sp_idle;
	 DEF_INST_top_DEF_CAN_FIRE_RL_sp_mark = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_sp_mark = DEF_INST_top_DEF_CAN_FIRE_RL_sp_mark;
	 DEF_INST_top_DEF_sp_txPend__h2240 = INST_top.INST_sp_txPend.METH_read();
	 INST_top.DEF_sp_txq_i_notFull____d3 = INST_top.INST_sp_txq.METH_i_notFull();
	 DEF_INST_top_DEF_CAN_FIRE_RL_sp_push = DEF_INST_top_DEF_sp_txPend__h2240 && INST_top.DEF_sp_txq_i_notFull____d3;
	 DEF_INST_top_DEF_WILL_FIRE_RL_sp_push = DEF_INST_top_DEF_CAN_FIRE_RL_sp_push;
	 DEF_INST_top_DEF_CAN_FIRE_RL_sp_status = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_sp_status = DEF_INST_top_DEF_CAN_FIRE_RL_sp_status;
	 INST_top.DEF_sp_st_read__5_EQ_3___d77 = (INST_top.DEF_sp_st_read____d25) == (tUInt8)3u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_sp_step = INST_top.DEF_sp_st_read__5_EQ_3___d77;
	 DEF_INST_top_DEF_WILL_FIRE_RL_sp_step = DEF_INST_top_DEF_CAN_FIRE_RL_sp_step;
	 INST_top.DEF_x__h3222 = INST_top.INST_sp_dly.METH_read();
	 INST_top.DEF_sp_st_read__5_EQ_4___d55 = (INST_top.DEF_sp_st_read____d25) == (tUInt8)4u;
	 DEF_INST_top_DEF_sp_dly_1_EQ_0___d62 = (INST_top.DEF_x__h3222) == (tUInt8)0u;
	 DEF_INST_top_DEF_sp_st_read__5_EQ_1_4_OR_sp_st_read__5_EQ_4_5_6_ETC___d60 = (((INST_top.DEF_sp_st_read____d25) == (tUInt8)1u || INST_top.DEF_sp_st_read__5_EQ_4___d55) || (INST_top.DEF_sp_st_read____d25) == (tUInt8)5u) || (INST_top.DEF_sp_st_read____d25) == (tUInt8)6u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_sp_waited = DEF_INST_top_DEF_sp_st_read__5_EQ_1_4_OR_sp_st_read__5_EQ_4_5_6_ETC___d60 && DEF_INST_top_DEF_sp_dly_1_EQ_0___d62;
	 DEF_INST_top_DEF_WILL_FIRE_RL_sp_waited = DEF_INST_top_DEF_CAN_FIRE_RL_sp_waited;
	 DEF_INST_top_DEF_CAN_FIRE_RL_sp_tick = DEF_INST_top_DEF_sp_st_read__5_EQ_1_4_OR_sp_st_read__5_EQ_4_5_6_ETC___d60 && !DEF_INST_top_DEF_sp_dly_1_EQ_0___d62;
	 DEF_INST_top_DEF_WILL_FIRE_RL_sp_tick = DEF_INST_top_DEF_CAN_FIRE_RL_sp_tick;
	 DEF_INST_top_DEF_CAN_FIRE_RL_timeout = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_timeout = DEF_INST_top_DEF_CAN_FIRE_RL_timeout;
	 DEF_INST_top_DEF_CAN_FIRE_RL_tmChk = (INST_top.DEF_ph__h6611) == (tUInt8)90u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_tmChk = DEF_INST_top_DEF_CAN_FIRE_RL_tmChk;
	 DEF_INST_top_DEF_CAN_FIRE_RL_wmA = (INST_top.DEF_ph__h6611) == (tUInt8)3u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_wmA = DEF_INST_top_DEF_CAN_FIRE_RL_wmA;
	 DEF_INST_top_DEF_CAN_FIRE_RL_wmB = (INST_top.DEF_ph__h6611) == (tUInt8)4u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_wmB = DEF_INST_top_DEF_CAN_FIRE_RL_wmB;
	 DEF_INST_top_DEF_CAN_FIRE_RL_wmC = (INST_top.DEF_ph__h6611) == (tUInt8)5u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_wmC = DEF_INST_top_DEF_CAN_FIRE_RL_wmC;
	 DEF_INST_top_DEF_CAN_FIRE_RL_wmE = (INST_top.DEF_ph__h6611) == (tUInt8)7u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_wmE = DEF_INST_top_DEF_CAN_FIRE_RL_wmE;
	 DEF_INST_top_DEF_CAN_FIRE_RL_wmD = (INST_top.DEF_ph__h6611) == (tUInt8)6u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_wmD = DEF_INST_top_DEF_CAN_FIRE_RL_wmD;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_sp_csTrack)
	   INST_top.RL_sp_csTrack();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_sp_status)
	   INST_top.RL_sp_status();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_sp_push)
	   INST_top.RL_sp_push();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_send)
	   INST_top.RL_send();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_timeout)
	   INST_top.RL_timeout();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csHoldB)
	   INST_top.RL_csHoldB();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csHoldC)
	   INST_top.RL_csHoldC();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csOffB)
	   INST_top.RL_csOffB();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csdA)
	   INST_top.RL_csdA();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csdC)
	   INST_top.RL_csdC();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dirCheck)
	   INST_top.RL_dirCheck();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dirWait)
	   INST_top.RL_dirWait();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fin)
	   INST_top.RL_fin();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_flush)
	   INST_top.RL_flush();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_flush2)
	   INST_top.RL_flush2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_flush3)
	   INST_top.RL_flush3();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_flush4)
	   INST_top.RL_flush4();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdB)
	   INST_top.RL_holdB();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdC)
	   INST_top.RL_holdC();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdE)
	   INST_top.RL_holdE();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdG)
	   INST_top.RL_holdG();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdJ2)
	   INST_top.RL_holdJ2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_lsbCheck)
	   INST_top.RL_lsbCheck();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_phaC)
	   INST_top.RL_phaC();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_lsbWait)
	   INST_top.RL_lsbWait();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ovfA)
	   INST_top.RL_ovfA();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ovfB)
	   INST_top.RL_ovfB();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ovfC)
	   INST_top.RL_ovfC();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_ovfM)
	   INST_top.RL_ovfM();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_phaB)
	   INST_top.RL_phaB();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r0m)
	   INST_top.RL_r0m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r0q)
	   INST_top.RL_r0q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r0s)
	   INST_top.RL_r0s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r10m)
	   INST_top.RL_r10m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r10q)
	   INST_top.RL_r10q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r10s)
	   INST_top.RL_r10s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r11q)
	   INST_top.RL_r11q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r11m)
	   INST_top.RL_r11m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r11s)
	   INST_top.RL_r11s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r1m)
	   INST_top.RL_r1m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r1q)
	   INST_top.RL_r1q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r1s)
	   INST_top.RL_r1s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r2m)
	   INST_top.RL_r2m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r2s)
	   INST_top.RL_r2s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r2q)
	   INST_top.RL_r2q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r3m)
	   INST_top.RL_r3m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r3q)
	   INST_top.RL_r3q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r4m)
	   INST_top.RL_r4m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r3s)
	   INST_top.RL_r3s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r4q)
	   INST_top.RL_r4q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r4s)
	   INST_top.RL_r4s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r5m)
	   INST_top.RL_r5m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r5q)
	   INST_top.RL_r5q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r5s)
	   INST_top.RL_r5s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r6m)
	   INST_top.RL_r6m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r6q)
	   INST_top.RL_r6q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r6s)
	   INST_top.RL_r6s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r7s)
	   INST_top.RL_r7s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r7m)
	   INST_top.RL_r7m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r7q)
	   INST_top.RL_r7q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r8m)
	   INST_top.RL_r8m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r8q)
	   INST_top.RL_r8q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r8s)
	   INST_top.RL_r8s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r9m)
	   INST_top.RL_r9m();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r9q)
	   INST_top.RL_r9q();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r9s)
	   INST_top.RL_r9s();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_recv)
	   INST_top.RL_recv();
	 INST_top.DEF_sp_rxq_i_notEmpty____d122 = INST_top.INST_sp_rxq.METH_i_notEmpty();
	 DEF_INST_top_DEF_CAN_FIRE_RL_sp_pop = INST_top.INST_sp_r_rxdata_data_acc.METH_whas() && INST_top.DEF_sp_rxq_i_notEmpty____d122;
	 DEF_INST_top_DEF_WILL_FIRE_RL_sp_pop = DEF_INST_top_DEF_CAN_FIRE_RL_sp_pop;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_sendDone)
	   INST_top.RL_sendDone();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_sp_pop)
	   INST_top.RL_sp_pop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_tmChk)
	   INST_top.RL_tmChk();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_loop)
	   INST_top.RL_loop();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csOffC)
	   INST_top.RL_csOffC();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csdD)
	   INST_top.RL_csdD();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csdE)
	   INST_top.RL_csdE();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdJ3)
	   INST_top.RL_holdJ3();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdK)
	   INST_top.RL_holdK();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_phaA)
	   INST_top.RL_phaA();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_phaD)
	   INST_top.RL_phaD();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r1w)
	   INST_top.RL_r1w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r4w)
	   INST_top.RL_r4w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_sp_idle)
	   INST_top.RL_sp_idle();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csdB)
	   INST_top.RL_csdB();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csdF)
	   INST_top.RL_csdF();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdF)
	   INST_top.RL_holdF();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdJ)
	   INST_top.RL_holdJ();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdL)
	   INST_top.RL_holdL();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_sp_load)
	   INST_top.RL_sp_load();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_sp_step)
	   INST_top.RL_sp_step();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csHoldA)
	   INST_top.RL_csHoldA();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csHoldD)
	   INST_top.RL_csHoldD();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_csOffA)
	   INST_top.RL_csOffA();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_dirSet)
	   INST_top.RL_dirSet();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdA)
	   INST_top.RL_holdA();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdD)
	   INST_top.RL_holdD();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_holdM)
	   INST_top.RL_holdM();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_lsbSet)
	   INST_top.RL_lsbSet();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r2w)
	   INST_top.RL_r2w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r3w)
	   INST_top.RL_r3w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r5w)
	   INST_top.RL_r5w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_sp_tick)
	   INST_top.RL_sp_tick();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_sp_waited)
	   INST_top.RL_sp_waited();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r0w)
	   INST_top.RL_r0w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r10w)
	   INST_top.RL_r10w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r11w)
	   INST_top.RL_r11w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r6w)
	   INST_top.RL_r6w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r7w)
	   INST_top.RL_r7w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r8w)
	   INST_top.RL_r8w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_setup)
	   INST_top.RL_setup();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_r9w)
	   INST_top.RL_r9w();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_wmA)
	   INST_top.RL_wmA();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_wmB)
	   INST_top.RL_wmB();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_wmC)
	   INST_top.RL_wmC();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_wmE)
	   INST_top.RL_wmE();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_wmD)
	   INST_top.RL_wmD();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_sp_mark)
	   INST_top.RL_sp_mark();
	 INST_top.INST_csHi.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_csSaw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_sp_csDrop.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_sp_ioIn.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_sp_r_rxdata_data_acc.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_sp_r_txdata_data_mod.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_sp_r_ip_rxwm_r.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_sp_r_ip_txwm_r.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_sp_r_rxdata_empty_r.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_sp_r_rxdata_data_r.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_sp_r_txdata_full_r.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_sp_r_sckdiv_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_sckmode_pha_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_sckmode_pol_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_csid_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_csdef_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_csmode_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_delay0_cssck_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_delay0_sckcs_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_delay1_intercs_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_delay1_interxfr_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_fmt_proto_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_fmt_endian_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_fmt_dir_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_fmt_len_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_txdata_data_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_txmark_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_rxmark_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_ie_txwm_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_r_ie_rxwm_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_txq.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_sp_rxq.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_sp_st.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_dly.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_div.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_half.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_bitn.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_shTx.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_shRx.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_txPend.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_csOn.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_csAct.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_csDrop.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_sp_idWas.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_modeWas.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_defWas.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_txIn.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_txOut.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_rxIn.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sp_rxOut.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_ph.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_s.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sent.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_got.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_cyc.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_bad.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sawCs.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_csNow.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_csSaw.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_csPins.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_csHi.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_onWas.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_sckWas.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_leadPend.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_tOn.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_tOff.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_tEdge.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mLead.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mTail.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mInact.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mGap.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_nOn.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_onMark.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_ovfN.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_nEdgeF.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mPerF.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vleadA.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vleadB.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vleadC.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vtailA.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vtailB.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vtailC.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vinactA.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vinactC.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vgapA.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vgapB.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vautoA.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_vautoB.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkSpiLines4Tb::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkSpiLines4Tb_instance = new MOD_mkSpiLines4Tb(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkSpiLines4Tb_instance->INST_sp_r_txdata_full_r.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_sp_r_rxdata_data_r.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_sp_r_rxdata_empty_r.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_sp_r_ip_txwm_r.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_sp_r_ip_rxwm_r.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_sp_r_txdata_data_mod.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_sp_r_rxdata_data_acc.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_sp_txq.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_sp_rxq.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_sp_ioIn.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_sp_csDrop.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_csSaw.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->INST_csHi.set_clk_0)("CLK");
  (mkSpiLines4Tb_instance->set_clk_0)("CLK");
}
void MODEL_mkSpiLines4Tb::destroy_model()
{
  delete mkSpiLines4Tb_instance;
  mkSpiLines4Tb_instance = NULL;
}
void MODEL_mkSpiLines4Tb::reset_model(bool asserted)
{
  (mkSpiLines4Tb_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkSpiLines4Tb::get_instance()
{
  return mkSpiLines4Tb_instance;
}

/* Fill in version numbers */
void MODEL_mkSpiLines4Tb::get_version(char const **name, char const **build)
{
  *name = "2026.01";
  *build = "9bd39e6f";
}

/* Get the model creation time */
time_t MODEL_mkSpiLines4Tb::get_creation_time()
{
  
  /* Mon Sep 21 15:42:19 UTC 2026 */
  return 1790005339llu;
}

/* State dumping function */
void MODEL_mkSpiLines4Tb::dump_state()
{
  (mkSpiLines4Tb_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkSpiLines4Tb & mkSpiLines4Tb_backing(tSimStateHdl simHdl)
{
  static MOD_mkSpiLines4Tb *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkSpiLines4Tb(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkSpiLines4Tb::dump_VCD_defs()
{
  (mkSpiLines4Tb_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkSpiLines4Tb::dump_VCD(tVCDDumpType dt)
{
  (mkSpiLines4Tb_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkSpiLines4Tb_backing(sim_hdl));
}
