/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Tue Sep 22 00:42:13 JST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkSpiRegsTbLines4.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkSpiRegsTbLines4::MODEL_mkSpiRegsTbLines4()
{
  mkSpiRegsTbLines4_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkSpiRegsTbLines4()
{
  MODEL_mkSpiRegsTbLines4 *model = new MODEL_mkSpiRegsTbLines4();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkSpiRegsTbLines4 &INST_top = *((MOD_mkSpiRegsTbLines4 *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_ph2__h1377;
	 tUInt8 DEF_INST_top_DEF_ph3___d193;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_run;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_race;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_race;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_run;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_warl;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_warl;
	 DEF_INST_top_DEF_ph3___d193 = INST_top.INST_ph3.METH_read();
	 DEF_INST_top_DEF_ph2__h1377 = INST_top.INST_ph2.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_race = DEF_INST_top_DEF_ph2__h1377 && !DEF_INST_top_DEF_ph3___d193;
	 DEF_INST_top_DEF_WILL_FIRE_RL_race = DEF_INST_top_DEF_CAN_FIRE_RL_race;
	 DEF_INST_top_DEF_CAN_FIRE_RL_run = !DEF_INST_top_DEF_ph2__h1377;
	 DEF_INST_top_DEF_WILL_FIRE_RL_run = DEF_INST_top_DEF_CAN_FIRE_RL_run;
	 DEF_INST_top_DEF_CAN_FIRE_RL_warl = DEF_INST_top_DEF_ph3___d193;
	 DEF_INST_top_DEF_WILL_FIRE_RL_warl = DEF_INST_top_DEF_CAN_FIRE_RL_warl && !DEF_INST_top_DEF_WILL_FIRE_RL_run;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_race)
	   INST_top.RL_race();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_run)
	   INST_top.RL_run();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_warl)
	   INST_top.RL_warl();
	 INST_top.INST_r_rxdata_data_acc.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_r_txdata_data_mod.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_r_ip_rxwm_r.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_r_ip_txwm_r.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_r_rxdata_empty_r.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_r_rxdata_data_r.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_r_txdata_full_r.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_r_sckdiv_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_sckmode_pha_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_sckmode_pol_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_csid_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_csdef_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_csmode_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_delay0_cssck_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_delay0_sckcs_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_delay1_intercs_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_delay1_interxfr_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_fmt_proto_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_fmt_endian_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_fmt_dir_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_fmt_len_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_txdata_data_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_txmark_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_rxmark_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_ie_txwm_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_r_ie_rxwm_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_step.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_rstp.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_bad.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_ph2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_ph3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_wstp.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkSpiRegsTbLines4::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkSpiRegsTbLines4_instance = new MOD_mkSpiRegsTbLines4(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkSpiRegsTbLines4_instance->INST_r_txdata_full_r.set_clk_0)("CLK");
  (mkSpiRegsTbLines4_instance->INST_r_rxdata_data_r.set_clk_0)("CLK");
  (mkSpiRegsTbLines4_instance->INST_r_rxdata_empty_r.set_clk_0)("CLK");
  (mkSpiRegsTbLines4_instance->INST_r_ip_txwm_r.set_clk_0)("CLK");
  (mkSpiRegsTbLines4_instance->INST_r_ip_rxwm_r.set_clk_0)("CLK");
  (mkSpiRegsTbLines4_instance->INST_r_txdata_data_mod.set_clk_0)("CLK");
  (mkSpiRegsTbLines4_instance->INST_r_rxdata_data_acc.set_clk_0)("CLK");
  (mkSpiRegsTbLines4_instance->set_clk_0)("CLK");
}
void MODEL_mkSpiRegsTbLines4::destroy_model()
{
  delete mkSpiRegsTbLines4_instance;
  mkSpiRegsTbLines4_instance = NULL;
}
void MODEL_mkSpiRegsTbLines4::reset_model(bool asserted)
{
  (mkSpiRegsTbLines4_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkSpiRegsTbLines4::get_instance()
{
  return mkSpiRegsTbLines4_instance;
}

/* Fill in version numbers */
void MODEL_mkSpiRegsTbLines4::get_version(char const **name, char const **build)
{
  *name = "2026.01";
  *build = "9bd39e6f";
}

/* Get the model creation time */
time_t MODEL_mkSpiRegsTbLines4::get_creation_time()
{
  
  /* Mon Sep 21 15:42:13 UTC 2026 */
  return 1790005333llu;
}

/* State dumping function */
void MODEL_mkSpiRegsTbLines4::dump_state()
{
  (mkSpiRegsTbLines4_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkSpiRegsTbLines4 & mkSpiRegsTbLines4_backing(tSimStateHdl simHdl)
{
  static MOD_mkSpiRegsTbLines4 *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkSpiRegsTbLines4(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkSpiRegsTbLines4::dump_VCD_defs()
{
  (mkSpiRegsTbLines4_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkSpiRegsTbLines4::dump_VCD(tVCDDumpType dt)
{
  (mkSpiRegsTbLines4_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkSpiRegsTbLines4_backing(sim_hdl));
}
