/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Tue Sep 22 00:42:13 JST 2026
 * 
 */

/* Generation options: */
#ifndef __model_mkSpiRegsTbLines4_h__
#define __model_mkSpiRegsTbLines4_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkSpiRegsTbLines4.h"

/* Class declaration for a model of mkSpiRegsTbLines4 */
class MODEL_mkSpiRegsTbLines4 : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkSpiRegsTbLines4 *mkSpiRegsTbLines4_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkSpiRegsTbLines4();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkSpiRegsTbLines4();
}

#endif /* ifndef __model_mkSpiRegsTbLines4_h__ */
