/*
 * Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
 * 
 * On Tue Sep 22 00:42:19 JST 2026
 * 
 */

/* Generation options: */
#ifndef __model_mkSpiLines4Tb_h__
#define __model_mkSpiLines4Tb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkSpiLines4Tb.h"

/* Class declaration for a model of mkSpiLines4Tb */
class MODEL_mkSpiLines4Tb : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkSpiLines4Tb *mkSpiLines4Tb_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkSpiLines4Tb();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkSpiLines4Tb();
}

#endif /* ifndef __model_mkSpiLines4Tb_h__ */
